"""检索引擎连接配置（从全局 settings 读取）。"""

from app.config import settings


# ── Elasticsearch ──
ES_HOST = settings.ES_HOST
ES_INDEX_CASE = settings.ES_INDEX_CASE
ES_INDEX_BUG = settings.ES_INDEX_BUG

# ── Milvus ──
MILVUS_HOST = settings.MILVUS_HOST
MILVUS_PORT = settings.MILVUS_PORT
MILVUS_COLLECTION_CASE = settings.MILVUS_COLLECTION_CASE
MILVUS_COLLECTION_BUG = settings.MILVUS_COLLECTION_BUG

# ── Embedding ──
EMBEDDING_PROVIDER = settings.EMBEDDING_PROVIDER
EMBEDDING_MODEL = settings.EMBEDDING_MODEL
EMBEDDING_DIM = settings.EMBEDDING_DIM
EMBEDDING_DEVICE = settings.EMBEDDING_DEVICE

# ── Ollama Embedding ──
OLLAMA_BASE_URL = settings.OLLAMA_BASE_URL
OLLAMA_EMBEDDING_MODEL = settings.OLLAMA_EMBEDDING_MODEL

# ── OpenAI 兼容 Embedding（OpenAI 官方 / 通义千问 / DeepSeek 等） ──
OPENAI_EMBEDDING_BASE_URL = settings.OPENAI_EMBEDDING_BASE_URL
OPENAI_EMBEDDING_API_KEY = settings.OPENAI_EMBEDDING_API_KEY
OPENAI_EMBEDDING_MODEL = settings.OPENAI_EMBEDDING_MODEL

# ── Azure OpenAI Embedding ──
AZURE_OPENAI_API_KEY = settings.AZURE_OPENAI_API_KEY
AZURE_OPENAI_ENDPOINT = settings.AZURE_OPENAI_ENDPOINT
AZURE_OPENAI_API_VERSION = settings.AZURE_OPENAI_API_VERSION
AZURE_EMBEDDING_DEPLOYMENT = settings.AZURE_EMBEDDING_DEPLOYMENT

# ── RRF ──
RRF_K: int = 60

# ── 默认召回数量 ──
DEFAULT_TOP_K: int = 20
