-- YouLai_Admin 数据库 (PostgreSQL 16+)
-- 从数据库直接导出 DDL，与后端 Model 完全一致

-- ----------------------------
-- 建表语句
-- ----------------------------

DROP TABLE IF EXISTS sys_config;
CREATE TABLE sys_config (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    config_name varchar(50) NOT NULL,
    config_key varchar(50) NOT NULL,
    config_value varchar(100) NOT NULL,
    remark varchar(255),
    create_time timestamp,
    create_by bigint,
    update_time timestamp,
    update_by bigint,
    is_deleted smallint DEFAULT 0 NOT NULL
)
    PRIMARY KEY (id)
);

COMMENT ON TABLE sys_config IS '系统配置表';

COMMENT ON COLUMN sys_config.config_name IS '配置名称';

COMMENT ON COLUMN sys_config.config_key IS '配置key';

COMMENT ON COLUMN sys_config.config_value IS '配置值';

COMMENT ON COLUMN sys_config.remark IS '备注';

COMMENT ON COLUMN sys_config.create_time IS '创建时间';

COMMENT ON COLUMN sys_config.create_by IS '创建人ID';

COMMENT ON COLUMN sys_config.update_time IS '更新时间';

COMMENT ON COLUMN sys_config.update_by IS '更新人ID';

COMMENT ON COLUMN sys_config.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';

DROP TABLE IF EXISTS sys_dept;
CREATE TABLE sys_dept (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    code varchar(100) NOT NULL,
    parent_id bigint DEFAULT 0,
    tree_path varchar(255) NOT NULL,
    sort smallint DEFAULT 0,
    status smallint DEFAULT 1,
    create_by bigint,
    create_time timestamp,
    update_by bigint,
    update_time timestamp,
    is_deleted smallint DEFAULT 0
)
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_code ON sys_dept (code);

COMMENT ON TABLE sys_dept IS '部门管理表';

COMMENT ON COLUMN sys_dept.id IS '主键';

COMMENT ON COLUMN sys_dept.name IS '部门名称';

COMMENT ON COLUMN sys_dept.code IS '部门编号';

COMMENT ON COLUMN sys_dept.parent_id IS '父节点id';

COMMENT ON COLUMN sys_dept.tree_path IS '父节点id路径';

COMMENT ON COLUMN sys_dept.sort IS '显示顺序';

COMMENT ON COLUMN sys_dept.status IS '状态(1-正常 0-禁用)';

COMMENT ON COLUMN sys_dept.create_by IS '创建人ID';

COMMENT ON COLUMN sys_dept.create_time IS '创建时间';

COMMENT ON COLUMN sys_dept.update_by IS '修改人ID';

COMMENT ON COLUMN sys_dept.update_time IS '更新时间';

COMMENT ON COLUMN sys_dept.is_deleted IS '逻辑删除标识(1-已删除 0-未删除)';

DROP TABLE IF EXISTS sys_dict;
CREATE TABLE sys_dict (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    dict_code varchar(50),
    name varchar(50),
    status smallint DEFAULT 0,
    remark varchar(255),
    create_time timestamp,
    create_by bigint,
    update_time timestamp,
    update_by bigint,
    is_deleted smallint DEFAULT 0
)
    PRIMARY KEY (id)
);
CREATE INDEX ON sys_dict (dict_code);

COMMENT ON TABLE sys_dict IS '数据字典类型表';

COMMENT ON COLUMN sys_dict.id IS '主键 ';

COMMENT ON COLUMN sys_dict.dict_code IS '类型编码';

COMMENT ON COLUMN sys_dict.name IS '类型名称';

COMMENT ON COLUMN sys_dict.status IS '状态(0:正常;1:禁用)';

COMMENT ON COLUMN sys_dict.remark IS '备注';

COMMENT ON COLUMN sys_dict.create_time IS '创建时间';

COMMENT ON COLUMN sys_dict.create_by IS '创建人ID';

COMMENT ON COLUMN sys_dict.update_time IS '更新时间';

COMMENT ON COLUMN sys_dict.update_by IS '修改人ID';

COMMENT ON COLUMN sys_dict.is_deleted IS '是否删除(1-删除，0-未删除)';

DROP TABLE IF EXISTS sys_dict_item;
CREATE TABLE sys_dict_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    dict_code varchar(50),
    value varchar(50),
    label varchar(100),
    tag_type varchar(50),
    status smallint DEFAULT 0,
    sort integer DEFAULT 0,
    remark varchar(255),
    create_time timestamp,
    create_by bigint,
    update_time timestamp,
    update_by bigint
)
    PRIMARY KEY (id)
);

COMMENT ON TABLE sys_dict_item IS '数据字典项表';

COMMENT ON COLUMN sys_dict_item.id IS '主键';

COMMENT ON COLUMN sys_dict_item.dict_code IS '关联字典编码，与sys_dict表中的dict_code对应';

COMMENT ON COLUMN sys_dict_item.value IS '字典项值';

COMMENT ON COLUMN sys_dict_item.label IS '字典项标签';

COMMENT ON COLUMN sys_dict_item.tag_type IS '标签类型，用于前端样式展示（如success、warning等）';

COMMENT ON COLUMN sys_dict_item.status IS '状态（1-正常，0-禁用）';

COMMENT ON COLUMN sys_dict_item.sort IS '排序';

COMMENT ON COLUMN sys_dict_item.remark IS '备注';

COMMENT ON COLUMN sys_dict_item.create_time IS '创建时间';

COMMENT ON COLUMN sys_dict_item.create_by IS '创建人ID';

COMMENT ON COLUMN sys_dict_item.update_time IS '更新时间';

COMMENT ON COLUMN sys_dict_item.update_by IS '修改人ID';

DROP TABLE IF EXISTS sys_log;
CREATE TABLE sys_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    module smallint NOT NULL,
    action_type smallint NOT NULL,
    title varchar(100) NOT NULL,
    content text,
    operator_id bigint,
    operator_name varchar(50),
    request_uri varchar(255),
    request_method varchar(10),
    ip varchar(45),
    province varchar(100),
    city varchar(100),
    device varchar(100),
    os varchar(100),
    browser varchar(100),
    status smallint DEFAULT 1,
    error_msg varchar(255),
    execution_time integer,
    create_time timestamp
)
    PRIMARY KEY (id)
);
CREATE INDEX ON sys_log (module, action_type, create_time);
CREATE INDEX ON sys_log (operator_id, create_time);
CREATE INDEX ON sys_log (create_time);

COMMENT ON TABLE sys_log IS '系统操作日志表';

COMMENT ON COLUMN sys_log.id IS '主键';

COMMENT ON COLUMN sys_log.module IS '模块，数字枚举，参考 LogModule 枚举';

COMMENT ON COLUMN sys_log.action_type IS '操作类型，数字枚举，参考 ActionType 枚举';

COMMENT ON COLUMN sys_log.title IS '前端显示标题';

COMMENT ON COLUMN sys_log.content IS '自定义日志内容';

COMMENT ON COLUMN sys_log.operator_id IS '操作人ID';

COMMENT ON COLUMN sys_log.operator_name IS '操作人名称';

COMMENT ON COLUMN sys_log.request_uri IS '请求路径';

COMMENT ON COLUMN sys_log.request_method IS '请求方法';

COMMENT ON COLUMN sys_log.ip IS 'IP地址';

COMMENT ON COLUMN sys_log.province IS '省份';

COMMENT ON COLUMN sys_log.city IS '城市';

COMMENT ON COLUMN sys_log.device IS '设备';

COMMENT ON COLUMN sys_log.os IS '操作系统';

COMMENT ON COLUMN sys_log.browser IS '浏览器';

COMMENT ON COLUMN sys_log.status IS '0失败 1成功';

COMMENT ON COLUMN sys_log.error_msg IS '错误信息';

COMMENT ON COLUMN sys_log.execution_time IS '执行时间(ms)';

COMMENT ON COLUMN sys_log.create_time IS '操作时间';

DROP TABLE IF EXISTS sys_menu;
CREATE TABLE sys_menu (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    parent_id bigint NOT NULL,
    tree_path varchar(255),
    name varchar(64) NOT NULL,
    type character(1) NOT NULL,
    route_name varchar(255),
    route_path varchar(128),
    component varchar(128),
    perm varchar(128),
    external_url varchar(512),
    always_show smallint DEFAULT 0,
    keep_alive smallint DEFAULT 0,
    visible smallint DEFAULT 1,
    sort integer DEFAULT 0,
    icon varchar(64),
    redirect varchar(128),
    create_time timestamp,
    update_time timestamp,
    params jsonb
)
    PRIMARY KEY (id)
);

COMMENT ON TABLE sys_menu IS '系统菜单表';

COMMENT ON COLUMN sys_menu.id IS 'ID';

COMMENT ON COLUMN sys_menu.parent_id IS '父菜单ID';

COMMENT ON COLUMN sys_menu.tree_path IS '父节点ID路径';

COMMENT ON COLUMN sys_menu.name IS '菜单名称';

COMMENT ON COLUMN sys_menu.type IS '菜单类型（C-目录 M-菜单 E-外链 B-按钮）';

COMMENT ON COLUMN sys_menu.route_name IS '路由名称（Vue Router 中用于命名路由）';

COMMENT ON COLUMN sys_menu.route_path IS '路由路径（Vue Router 中定义的 URL 路径）';

COMMENT ON COLUMN sys_menu.component IS '组件路径（组件页面完整路径，相对于 src/views/，缺省后缀 .vue）';

COMMENT ON COLUMN sys_menu.perm IS '【按钮】权限标识';

COMMENT ON COLUMN sys_menu.external_url IS '外链地址';

COMMENT ON COLUMN sys_menu.always_show IS '【目录】只有一个子路由是否始终显示（1-是 0-否）';

COMMENT ON COLUMN sys_menu.keep_alive IS '【菜单】是否开启页面缓存（1-是 0-否）';

COMMENT ON COLUMN sys_menu.visible IS '显示状态（1-显示 0-隐藏）';

COMMENT ON COLUMN sys_menu.sort IS '排序';

COMMENT ON COLUMN sys_menu.icon IS '菜单图标';

COMMENT ON COLUMN sys_menu.redirect IS '跳转路径';

COMMENT ON COLUMN sys_menu.create_time IS '创建时间';

COMMENT ON COLUMN sys_menu.update_time IS '更新时间';

COMMENT ON COLUMN sys_menu.params IS '路由参数';

DROP TABLE IF EXISTS sys_notice;
CREATE TABLE sys_notice (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50),
    content text,
    type smallint NOT NULL,
    level varchar(5) NOT NULL,
    target_type smallint NOT NULL,
    target_user_ids varchar(255),
    publisher_id bigint,
    publish_status smallint DEFAULT 0,
    publish_time timestamp,
    revoke_time timestamp,
    create_by bigint NOT NULL,
    create_time timestamp NOT NULL,
    update_by bigint,
    update_time timestamp,
    is_deleted smallint DEFAULT 0
)
    PRIMARY KEY (id)
);

COMMENT ON TABLE sys_notice IS '系统通知公告表';

COMMENT ON COLUMN sys_notice.title IS '通知标题';

COMMENT ON COLUMN sys_notice.content IS '通知内容';

COMMENT ON COLUMN sys_notice.type IS '通知类型（关联字典编码：notice_type）';

COMMENT ON COLUMN sys_notice.level IS '通知等级（字典code：notice_level）';

COMMENT ON COLUMN sys_notice.target_type IS '目标类型（1: 全体, 2: 指定）';

COMMENT ON COLUMN sys_notice.target_user_ids IS '目标人ID集合（多个使用英文逗号,分割）';

COMMENT ON COLUMN sys_notice.publisher_id IS '发布人ID';

COMMENT ON COLUMN sys_notice.publish_status IS '发布状态（0: 未发布, 1: 已发布, -1: 已撤回）';

COMMENT ON COLUMN sys_notice.publish_time IS '发布时间';

COMMENT ON COLUMN sys_notice.revoke_time IS '撤回时间';

COMMENT ON COLUMN sys_notice.create_by IS '创建人ID';

COMMENT ON COLUMN sys_notice.create_time IS '创建时间';

COMMENT ON COLUMN sys_notice.update_by IS '更新人ID';

COMMENT ON COLUMN sys_notice.update_time IS '更新时间';

COMMENT ON COLUMN sys_notice.is_deleted IS '是否删除（0: 未删除, 1: 已删除）';

DROP TABLE IF EXISTS sys_role;
CREATE TABLE sys_role (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(64) NOT NULL,
    code varchar(32) NOT NULL,
    sort integer,
    status smallint DEFAULT 1,
    data_scope smallint,
    create_by bigint,
    create_time timestamp,
    update_by bigint,
    update_time timestamp,
    is_deleted smallint DEFAULT 0
)
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_name ON sys_role (name);
CREATE UNIQUE INDEX uk_role_code ON sys_role (code);

COMMENT ON TABLE sys_role IS '系统角色表';

COMMENT ON COLUMN sys_role.name IS '角色名称';

COMMENT ON COLUMN sys_role.code IS '角色编码';

COMMENT ON COLUMN sys_role.sort IS '显示顺序';

COMMENT ON COLUMN sys_role.status IS '角色状态(1-正常 0-停用)';

COMMENT ON COLUMN sys_role.data_scope IS '数据权限(1-所有数据 2-部门及子部门数据 3-本部门数据 4-本人数据 5-自定义部门数据)';

COMMENT ON COLUMN sys_role.create_by IS '创建人 ID';

COMMENT ON COLUMN sys_role.create_time IS '创建时间';

COMMENT ON COLUMN sys_role.update_by IS '更新人ID';

COMMENT ON COLUMN sys_role.update_time IS '更新时间';

COMMENT ON COLUMN sys_role.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';

DROP TABLE IF EXISTS sys_role_dept;
CREATE TABLE sys_role_dept (
    role_id bigint NOT NULL,
    dept_id bigint NOT NULL
)
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_roleid_deptid ON sys_role_dept (role_id, dept_id);

COMMENT ON TABLE sys_role_dept IS '角色部门关联表';

COMMENT ON COLUMN sys_role_dept.role_id IS '角色ID';

COMMENT ON COLUMN sys_role_dept.dept_id IS '部门ID';

DROP TABLE IF EXISTS sys_role_menu;
CREATE TABLE sys_role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL
)
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_roleid_menuid ON sys_role_menu (role_id, menu_id);

COMMENT ON TABLE sys_role_menu IS '角色菜单关联表';

COMMENT ON COLUMN sys_role_menu.role_id IS '角色ID';

COMMENT ON COLUMN sys_role_menu.menu_id IS '菜单ID';

DROP TABLE IF EXISTS sys_user;
CREATE TABLE sys_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(64),
    nickname varchar(64),
    gender smallint DEFAULT 1,
    password varchar(100),
    dept_id bigint,
    avatar varchar(255),
    mobile varchar(20),
    status smallint DEFAULT 1,
    email varchar(128),
    create_time timestamp,
    create_by bigint,
    update_time timestamp,
    update_by bigint,
    is_deleted smallint DEFAULT 0
)
    PRIMARY KEY (id)
);

COMMENT ON TABLE sys_user IS '系统用户表';

COMMENT ON COLUMN sys_user.username IS '用户名';

COMMENT ON COLUMN sys_user.nickname IS '昵称';

COMMENT ON COLUMN sys_user.gender IS '性别((1-男 2-女 0-保密)';

COMMENT ON COLUMN sys_user.password IS '密码';

COMMENT ON COLUMN sys_user.dept_id IS '部门ID';

COMMENT ON COLUMN sys_user.avatar IS '用户头像';

COMMENT ON COLUMN sys_user.mobile IS '联系方式';

COMMENT ON COLUMN sys_user.status IS '状态(1-正常 0-禁用)';

COMMENT ON COLUMN sys_user.email IS '用户邮箱';

COMMENT ON COLUMN sys_user.create_time IS '创建时间';

COMMENT ON COLUMN sys_user.create_by IS '创建人ID';

COMMENT ON COLUMN sys_user.update_time IS '更新时间';

COMMENT ON COLUMN sys_user.update_by IS '修改人ID';

COMMENT ON COLUMN sys_user.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';

DROP TABLE IF EXISTS sys_user_notice;
CREATE TABLE sys_user_notice (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    notice_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_read smallint DEFAULT 0,
    read_time timestamp,
    create_time timestamp NOT NULL,
    update_time timestamp,
    is_deleted smallint DEFAULT 0
)
    PRIMARY KEY (id)
);

COMMENT ON TABLE sys_user_notice IS '用户通知公告关联表';

COMMENT ON COLUMN sys_user_notice.id IS 'id';

COMMENT ON COLUMN sys_user_notice.notice_id IS '公共通知id';

COMMENT ON COLUMN sys_user_notice.user_id IS '用户id';

COMMENT ON COLUMN sys_user_notice.is_read IS '读取状态（0: 未读, 1: 已读）';

COMMENT ON COLUMN sys_user_notice.read_time IS '阅读时间';

COMMENT ON COLUMN sys_user_notice.create_time IS '创建时间';

COMMENT ON COLUMN sys_user_notice.update_time IS '更新时间';

COMMENT ON COLUMN sys_user_notice.is_deleted IS '逻辑删除(0: 未删除, 1: 已删除)';

DROP TABLE IF EXISTS sys_user_role;
CREATE TABLE sys_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
)
    PRIMARY KEY (id)
);

COMMENT ON TABLE sys_user_role IS '用户角色关联表';

COMMENT ON COLUMN sys_user_role.user_id IS '用户ID';

COMMENT ON COLUMN sys_user_role.role_id IS '角色ID';

DROP TABLE IF EXISTS sys_user_social;
CREATE TABLE sys_user_social (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    platform varchar(20) NOT NULL,
    openid varchar(64) NOT NULL,
    unionid varchar(64) DEFAULT NULL::varchar,
    nickname varchar(64) DEFAULT NULL::varchar,
    avatar varchar(255) DEFAULT NULL::varchar,
    session_key varchar(128) DEFAULT NULL::varchar,
    verified smallint DEFAULT 1,
    create_time timestamp,
    update_time timestamp
)
    PRIMARY KEY (id)
);
CREATE UNIQUE INDEX uk_platform_openid ON sys_user_social (platform, openid);
CREATE INDEX ON sys_user_social (unionid);
CREATE INDEX ON sys_user_social (user_id);

COMMENT ON TABLE sys_user_social IS '用户第三方账号绑定表';

COMMENT ON COLUMN sys_user_social.id IS '主键ID';

COMMENT ON COLUMN sys_user_social.user_id IS '用户ID';

COMMENT ON COLUMN sys_user_social.platform IS '平台类型(WECHAT_MINI/WECHAT_MP/ALIPAY/QQ/APPLE)';

COMMENT ON COLUMN sys_user_social.openid IS '平台openid';

COMMENT ON COLUMN sys_user_social.unionid IS '微信unionid';

COMMENT ON COLUMN sys_user_social.nickname IS '第三方昵称';

COMMENT ON COLUMN sys_user_social.avatar IS '第三方头像URL';

COMMENT ON COLUMN sys_user_social.session_key IS '微信session_key';

COMMENT ON COLUMN sys_user_social.verified IS '是否已验证(1-已验证 0-未验证)';

COMMENT ON COLUMN sys_user_social.create_time IS '绑定时间';

COMMENT ON COLUMN sys_user_social.update_time IS '更新时间';

-- ----------------------------
-- 种子数据
-- ----------------------------

-- Data for Name: sys_config; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_config VALUES (1, '系统限流QPS', 'IP_QPS_THRESHOLD_LIMIT', '10', '单个IP请求的最大每秒查询数（QPS）阈值Key', '2026-07-30 20:08:42.073333', 1, NULL, NULL, 0);

-- Data for Name: sys_dept; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_dept VALUES (1, '有来技术', 'YOULAI', 0, '0', 1, 1, 1, NULL, 1, '2026-07-30 20:08:41.803636', 0);
INSERT INTO sys_dept VALUES (2, '研发部门', 'RD001', 1, '0,1', 1, 1, 2, NULL, 2, '2026-07-30 20:08:41.804558', 0);
INSERT INTO sys_dept VALUES (3, '测试部门', 'QA001', 1, '0,1', 1, 1, 2, NULL, 2, '2026-07-30 20:08:41.805213', 0);

-- Data for Name: sys_dict; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_dict VALUES (1, 'gender', '性别', 1, NULL, '2026-07-30 20:08:41.819334', 1, '2026-07-30 20:08:41.819334', 1, 0);
INSERT INTO sys_dict VALUES (2, 'notice_type', '通知类型', 1, NULL, '2026-07-30 20:08:41.820109', 1, '2026-07-30 20:08:41.820109', 1, 0);
INSERT INTO sys_dict VALUES (3, 'notice_level', '通知级别', 1, NULL, '2026-07-30 20:08:41.820713', 1, '2026-07-30 20:08:41.820713', 1, 0);

-- Data for Name: sys_dict_item; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_dict_item VALUES (1, 'gender', '1', '男', 'primary', 1, 1, NULL, '2026-07-30 20:08:41.83746', 1, '2026-07-30 20:08:41.83746', 1);
INSERT INTO sys_dict_item VALUES (2, 'gender', '2', '女', 'danger', 1, 2, NULL, '2026-07-30 20:08:41.838232', 1, '2026-07-30 20:08:41.838232', 1);
INSERT INTO sys_dict_item VALUES (3, 'gender', '0', '保密', 'info', 1, 3, NULL, '2026-07-30 20:08:41.838893', 1, '2026-07-30 20:08:41.838893', 1);
INSERT INTO sys_dict_item VALUES (4, 'notice_type', '1', '系统升级', 'success', 1, 1, '', '2026-07-30 20:08:41.839563', 1, '2026-07-30 20:08:41.839563', 1);
INSERT INTO sys_dict_item VALUES (5, 'notice_type', '2', '系统维护', 'primary', 1, 2, '', '2026-07-30 20:08:41.840185', 1, '2026-07-30 20:08:41.840185', 1);
INSERT INTO sys_dict_item VALUES (6, 'notice_type', '3', '安全警告', 'danger', 1, 3, '', '2026-07-30 20:08:41.840876', 1, '2026-07-30 20:08:41.840876', 1);
INSERT INTO sys_dict_item VALUES (7, 'notice_type', '4', '假期通知', 'success', 1, 4, '', '2026-07-30 20:08:41.841477', 1, '2026-07-30 20:08:41.841477', 1);
INSERT INTO sys_dict_item VALUES (8, 'notice_type', '5', '公司新闻', 'primary', 1, 5, '', '2026-07-30 20:08:41.842102', 1, '2026-07-30 20:08:41.842102', 1);
INSERT INTO sys_dict_item VALUES (9, 'notice_type', '99', '其他', 'info', 1, 99, '', '2026-07-30 20:08:41.842708', 1, '2026-07-30 20:08:41.842708', 1);
INSERT INTO sys_dict_item VALUES (10, 'notice_level', 'L', '低', 'info', 1, 1, '', '2026-07-30 20:08:41.843334', 1, '2026-07-30 20:08:41.843334', 1);
INSERT INTO sys_dict_item VALUES (11, 'notice_level', 'M', '中', 'warning', 1, 2, '', '2026-07-30 20:08:41.843919', 1, '2026-07-30 20:08:41.843919', 1);
INSERT INTO sys_dict_item VALUES (12, 'notice_level', 'H', '高', 'danger', 1, 3, '', '2026-07-30 20:08:41.844519', 1, '2026-07-30 20:08:41.844519', 1);

-- Data for Name: sys_menu; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_menu VALUES (3020, 3000, '0,3000', '任务管理', 'M', 'AITCTask', 'tasks', 'aitc/task', NULL, NULL, 0, 1, 1, 2, 'el-icon-Collection', NULL, '2026-07-31 21:39:12.23725', '2026-08-01 23:19:03.112315', '[]');
INSERT INTO sys_menu VALUES (3080, 3000, '0,3000', '规范管理', 'M', 'AITCSpec', 'specs', 'aitc/spec', 'aitc:spec:list', NULL, 0, 1, 1, 8, 'document', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3081, 3080, '0,3000,3080', '规范查询', 'B', NULL, '', NULL, 'aitc:spec:list', NULL, 0, 0, 1, 1, '', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3082, 3080, '0,3000,3080', '规范创建', 'B', NULL, '', NULL, 'aitc:spec:create', NULL, 0, 0, 1, 2, '', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3083, 3080, '0,3000,3080', '规范编辑', 'B', NULL, '', NULL, 'aitc:spec:update', NULL, 0, 0, 1, 3, '', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3084, 3080, '0,3000,3080', '规范删除', 'B', NULL, '', NULL, 'aitc:spec:delete', NULL, 0, 0, 1, 4, '', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3074, 1, '0,3074', 'AI日志', 'M', 'LlmLog', 'llm-log', 'system/llm-log/index', 'sys:llm-log:list', NULL, 0, 0, 1, 99, 'monitor', NULL, NULL, '2026-08-05 23:40:10.597986', NULL);
INSERT INTO sys_menu VALUES (3000, 0, '0', '工作区', 'C', NULL, '/aitc', 'Layout', NULL, NULL, 0, 0, 1, 2, 'el-icon-Box', '', '2026-07-31 21:39:12.23725', '2026-08-08 16:49:41.165628', '[]');
INSERT INTO sys_menu VALUES (3010, 3000, '0,3010', '用例管理', 'M', 'AITCCases', 'cases', 'aitc/case', NULL, NULL, 0, 1, 1, 1, 'el-icon-List', NULL, '2026-07-31 21:39:12.23725', '2026-08-08 16:51:23.795179', '[]');
INSERT INTO sys_menu VALUES (3025, 3020, '0,3000,3020', '停止任务', 'B', NULL, '', NULL, 'aitc:task:stop', NULL, 0, 0, 1, 4, '', NULL, '2026-08-08 22:50:41.975839', '2026-08-08 22:50:41.975839', NULL);
INSERT INTO sys_menu VALUES (3011, 3010, '0,3000,3010', '用例查询', 'B', NULL, '', NULL, 'aitc:case:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3012, 3010, '0,3000,3010', '用例导入', 'B', NULL, '', NULL, 'aitc:case:import', NULL, 0, 0, 1, 2, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3013, 3010, '0,3000,3010', '用例编辑', 'B', NULL, '', NULL, 'aitc:case:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3014, 3010, '0,3000,3010', '用例删除', 'B', NULL, '', NULL, 'aitc:case:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3015, 3010, '0,3000,3010', '标记核心', 'B', NULL, '', NULL, 'aitc:case:core', NULL, 0, 0, 1, 5, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (251, 1, '0,1', '字典项', 'M', 'DictItem', 'dict-item', 'system/dict/dict-item', NULL, NULL, 0, 1, 1, 6, '', NULL, '2026-07-30 20:08:41.887077', '2026-07-30 20:08:41.887077', NULL);
INSERT INTO sys_menu VALUES (260, 1, '0,1', '系统日志', 'M', 'Log', 'log', 'system/log/index', NULL, NULL, 0, 1, 1, 7, 'document', NULL, '2026-07-30 20:08:41.890096', '2026-07-30 20:08:41.890096', NULL);
INSERT INTO sys_menu VALUES (270, 1, '0,1', '系统配置', 'M', 'Config', 'config', 'system/config/index', NULL, NULL, 0, 1, 1, 8, 'setting', NULL, '2026-07-30 20:08:41.891272', '2026-07-30 20:08:41.891272', NULL);
INSERT INTO sys_menu VALUES (2701, 270, '0,1,270', '系统配置查询', 'B', NULL, '', NULL, 'sys:config:list', NULL, 0, 1, 1, 1, '', NULL, '2026-07-30 20:08:41.89193', '2026-07-30 20:08:41.89193', NULL);
INSERT INTO sys_menu VALUES (2702, 270, '0,1,270', '系统配置新增', 'B', NULL, '', NULL, 'sys:config:create', NULL, 0, 1, 1, 2, '', NULL, '2026-07-30 20:08:41.892537', '2026-07-30 20:08:41.892537', NULL);
INSERT INTO sys_menu VALUES (2703, 270, '0,1,270', '系统配置修改', 'B', NULL, '', NULL, 'sys:config:update', NULL, 0, 1, 1, 3, '', NULL, '2026-07-30 20:08:41.893122', '2026-07-30 20:08:41.893122', NULL);
INSERT INTO sys_menu VALUES (2704, 270, '0,1,270', '系统配置删除', 'B', NULL, '', NULL, 'sys:config:delete', NULL, 0, 1, 1, 4, '', NULL, '2026-07-30 20:08:41.893745', '2026-07-30 20:08:41.893745', NULL);
INSERT INTO sys_menu VALUES (2705, 270, '0,1,270', '系统配置刷新', 'B', NULL, '', NULL, 'sys:config:refresh', NULL, 0, 1, 1, 5, '', NULL, '2026-07-30 20:08:41.894378', '2026-07-30 20:08:41.894378', NULL);
INSERT INTO sys_menu VALUES (2805, 280, '0,1,280', '通知发布', 'B', NULL, '', NULL, 'sys:notice:publish', NULL, 0, 1, 1, 5, '', NULL, '2026-07-30 20:08:41.898156', '2026-07-30 20:08:41.898156', NULL);
INSERT INTO sys_menu VALUES (2806, 280, '0,1,280', '通知撤回', 'B', NULL, '', NULL, 'sys:notice:revoke', NULL, 0, 1, 1, 6, '', NULL, '2026-07-30 20:08:41.898891', '2026-07-30 20:08:41.898891', NULL);
INSERT INTO sys_menu VALUES (3016, 3010, '0,3000,3010', '项目查询', 'B', NULL, '', NULL, 'aitc:project:list', NULL, 0, 0, 1, 6, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (1, 0, '0', '系统管理', 'C', NULL, '/system', 'Layout', NULL, NULL, 0, 0, 1, 2, 'system', '/system/user', '2026-07-30 20:08:41.862986', '2026-07-30 22:26:18.116852', '[]');
INSERT INTO sys_menu VALUES (220, 1, '0,1', '角色管理', 'M', 'Role', 'role', 'system/role/index', NULL, NULL, 0, 1, 1, 2, 'role', NULL, '2026-07-30 20:08:41.873884', '2026-07-30 20:08:41.873884', NULL);
INSERT INTO sys_menu VALUES (3060, 3000, '0,3000', '用例审核', 'M', 'CaseReviewIndex', 'review', 'aitc/task/case-review-index', NULL, NULL, 0, 1, 0, 6, 'gitcode', NULL, '2026-07-31 21:39:12.23725', '2026-08-05 00:40:25.548695', '[]');
INSERT INTO sys_menu VALUES (3024, 3010, '0,3000,3010', '标记样本', 'B', NULL, '', NULL, 'aitc:case:sample', NULL, 0, 0, 1, 10, '', NULL, '2026-08-02 14:42:51.28289', '2026-08-02 14:42:51.28289', NULL);
INSERT INTO sys_menu VALUES (210, 1, '0,1', '用户管理', 'M', 'User', 'user', 'system/user/index', NULL, NULL, 0, 1, 1, 1, 'el-icon-User', NULL, '2026-07-30 20:08:41.868853', '2026-07-30 20:08:41.868853', NULL);
INSERT INTO sys_menu VALUES (230, 1, '0,1', '菜单管理', 'M', 'SysMenu', 'menu', 'system/menu/index', NULL, NULL, 0, 1, 1, 3, 'menu', NULL, '2026-07-30 20:08:41.877478', '2026-07-30 20:08:41.877478', NULL);
INSERT INTO sys_menu VALUES (240, 1, '0,1', '部门管理', 'M', 'Dept', 'dept', 'system/dept/index', NULL, NULL, 0, 1, 1, 4, 'tree', NULL, '2026-07-30 20:08:41.880583', '2026-07-30 20:08:41.880583', NULL);
INSERT INTO sys_menu VALUES (250, 1, '0,1', '字典管理', 'M', 'Dict', 'dict', 'system/dict/index', NULL, NULL, 0, 1, 1, 5, 'dict', NULL, '2026-07-30 20:08:41.883995', '2026-07-30 20:08:41.883995', NULL);
INSERT INTO sys_menu VALUES (3071, 3070, '0,3000,3070', '脚本查询', 'B', NULL, '', NULL, 'aitc:script:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (2104, 210, '0,1,210', '用户删除', 'B', NULL, '', NULL, 'sys:user:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.871482', '2026-07-30 20:08:41.871482', NULL);
INSERT INTO sys_menu VALUES (2105, 210, '0,1,210', '重置密码', 'B', NULL, '', NULL, 'sys:user:reset-password', NULL, 0, 0, 1, 5, '', NULL, '2026-07-30 20:08:41.872076', '2026-07-30 20:08:41.872076', NULL);
INSERT INTO sys_menu VALUES (3072, 3070, '0,3000,3070', '脚本编辑', 'B', NULL, '', NULL, 'aitc:script:update', NULL, 0, 0, 1, 2, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3041, 3040, '0,3000,3040', '样本查询', 'B', NULL, '', NULL, 'aitc:sample:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3042, 3040, '0,3000,3040', '样本创建', 'B', NULL, '', NULL, 'aitc:sample:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3043, 3040, '0,3000,3040', '样本编辑', 'B', NULL, '', NULL, 'aitc:sample:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3044, 3040, '0,3000,3040', '样本删除', 'B', NULL, '', NULL, 'aitc:sample:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (2106, 210, '0,1,210', '用户导入', 'B', NULL, '', NULL, 'sys:user:import', NULL, 0, 0, 1, 6, '', NULL, '2026-07-30 20:08:41.872671', '2026-07-30 20:08:41.872671', NULL);
INSERT INTO sys_menu VALUES (2107, 210, '0,1,210', '用户导出', 'B', NULL, '', NULL, 'sys:user:export', NULL, 0, 0, 1, 7, '', NULL, '2026-07-30 20:08:41.873263', '2026-07-30 20:08:41.873263', NULL);
INSERT INTO sys_menu VALUES (2201, 220, '0,1,220', '角色查询', 'B', NULL, '', NULL, 'sys:role:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.874462', '2026-07-30 20:08:41.874462', NULL);
INSERT INTO sys_menu VALUES (2202, 220, '0,1,220', '角色新增', 'B', NULL, '', NULL, 'sys:role:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.875102', '2026-07-30 20:08:41.875102', NULL);
INSERT INTO sys_menu VALUES (2203, 220, '0,1,220', '角色编辑', 'B', NULL, '', NULL, 'sys:role:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.875692', '2026-07-30 20:08:41.875692', NULL);
INSERT INTO sys_menu VALUES (2204, 220, '0,1,220', '角色删除', 'B', NULL, '', NULL, 'sys:role:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.876291', '2026-07-30 20:08:41.876291', NULL);
INSERT INTO sys_menu VALUES (2512, 251, '0,1,251', '字典项新增', 'B', NULL, '', NULL, 'sys:dict-item:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.888326', '2026-07-30 20:08:41.888326', NULL);
INSERT INTO sys_menu VALUES (2513, 251, '0,1,251', '字典项编辑', 'B', NULL, '', NULL, 'sys:dict-item:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.888919', '2026-07-30 20:08:41.888919', NULL);
INSERT INTO sys_menu VALUES (2514, 251, '0,1,251', '字典项删除', 'B', NULL, '', NULL, 'sys:dict-item:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.889517', '2026-07-30 20:08:41.889517', NULL);
INSERT INTO sys_menu VALUES (2601, 260, '0,1,260', '日志查询', 'B', NULL, '', NULL, 'sys:log:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.890674', '2026-07-30 20:08:41.890674', NULL);
INSERT INTO sys_menu VALUES (280, 1, '0,1', '通知公告', 'M', 'Notice', 'notice', 'system/notice/index', NULL, NULL, 0, 0, 1, 9, '', NULL, '2026-07-30 20:08:41.895021', '2026-07-30 20:08:41.895021', NULL);
INSERT INTO sys_menu VALUES (2801, 280, '0,1,280', '通知查询', 'B', NULL, '', NULL, 'sys:notice:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.895612', '2026-07-30 20:08:41.895612', NULL);
INSERT INTO sys_menu VALUES (2802, 280, '0,1,280', '通知新增', 'B', NULL, '', NULL, 'sys:notice:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.896196', '2026-07-30 20:08:41.896196', NULL);
INSERT INTO sys_menu VALUES (2803, 280, '0,1,280', '通知编辑', 'B', NULL, '', NULL, 'sys:notice:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.896765', '2026-07-30 20:08:41.896765', NULL);
INSERT INTO sys_menu VALUES (2804, 280, '0,1,280', '通知删除', 'B', NULL, '', NULL, 'sys:notice:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.897406', '2026-07-30 20:08:41.897406', NULL);
INSERT INTO sys_menu VALUES (3017, 3010, '0,3000,3010', '项目创建', 'B', NULL, '', NULL, 'aitc:project:create', NULL, 0, 0, 1, 7, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3018, 3010, '0,3000,3010', '项目编辑', 'B', NULL, '', NULL, 'aitc:project:update', NULL, 0, 0, 1, 8, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3019, 3010, '0,3000,3010', '项目删除', 'B', NULL, '', NULL, 'aitc:project:delete', NULL, 0, 0, 1, 9, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3021, 3020, '0,3000,3020', '任务查询', 'B', NULL, '', NULL, 'aitc:task:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3022, 3020, '0,3000,3020', '创建任务', 'B', NULL, '', NULL, 'aitc:task:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3023, 3020, '0,3000,3020', '确认任务', 'B', NULL, '', NULL, 'aitc:task:confirm', NULL, 0, 0, 1, 3, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3070, 3000, '0,3070', '脚本库', 'M', 'AITCScript', 'scripts', 'aitc/script', NULL, NULL, 0, 1, 0, 7, 'code', NULL, '2026-07-31 21:39:12.23725', '2026-08-10 16:48:48.186533', '[]');
INSERT INTO sys_menu VALUES (2101, 210, '0,1,210', '用户查询', 'B', NULL, '', NULL, 'sys:user:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.869499', '2026-07-30 20:08:41.869499', NULL);
INSERT INTO sys_menu VALUES (2102, 210, '0,1,210', '用户新增', 'B', NULL, '', NULL, 'sys:user:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.870208', '2026-07-30 20:08:41.870208', NULL);
INSERT INTO sys_menu VALUES (2103, 210, '0,1,210', '用户编辑', 'B', NULL, '', NULL, 'sys:user:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.870855', '2026-07-30 20:08:41.870855', NULL);
INSERT INTO sys_menu VALUES (2205, 220, '0,1,220', '角色分配权限', 'B', NULL, '', NULL, 'sys:role:assign', NULL, 0, 0, 1, 5, '', NULL, '2026-07-30 20:08:41.876884', '2026-07-30 20:08:41.876884', NULL);
INSERT INTO sys_menu VALUES (2301, 230, '0,1,230', '菜单查询', 'B', NULL, '', NULL, 'sys:menu:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.878089', '2026-07-30 20:08:41.878089', NULL);
INSERT INTO sys_menu VALUES (2302, 230, '0,1,230', '菜单新增', 'B', NULL, '', NULL, 'sys:menu:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.878692', '2026-07-30 20:08:41.878692', NULL);
INSERT INTO sys_menu VALUES (2303, 230, '0,1,230', '菜单编辑', 'B', NULL, '', NULL, 'sys:menu:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.879343', '2026-07-30 20:08:41.879343', NULL);
INSERT INTO sys_menu VALUES (2304, 230, '0,1,230', '菜单删除', 'B', NULL, '', NULL, 'sys:menu:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.879947', '2026-07-30 20:08:41.879947', NULL);
INSERT INTO sys_menu VALUES (2401, 240, '0,1,240', '部门查询', 'B', NULL, '', NULL, 'sys:dept:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.881354', '2026-07-30 20:08:41.881354', NULL);
INSERT INTO sys_menu VALUES (2402, 240, '0,1,240', '部门新增', 'B', NULL, '', NULL, 'sys:dept:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.882085', '2026-07-30 20:08:41.882085', NULL);
INSERT INTO sys_menu VALUES (2403, 240, '0,1,240', '部门编辑', 'B', NULL, '', NULL, 'sys:dept:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.882734', '2026-07-30 20:08:41.882734', NULL);
INSERT INTO sys_menu VALUES (2404, 240, '0,1,240', '部门删除', 'B', NULL, '', NULL, 'sys:dept:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.88336', '2026-07-30 20:08:41.88336', NULL);
INSERT INTO sys_menu VALUES (2501, 250, '0,1,250', '字典查询', 'B', NULL, '', NULL, 'sys:dict:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.884631', '2026-07-30 20:08:41.884631', NULL);
INSERT INTO sys_menu VALUES (2502, 250, '0,1,250', '字典新增', 'B', NULL, '', NULL, 'sys:dict:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.885251', '2026-07-30 20:08:41.885251', NULL);
INSERT INTO sys_menu VALUES (2503, 250, '0,1,250', '字典编辑', 'B', NULL, '', NULL, 'sys:dict:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.88585', '2026-07-30 20:08:41.88585', NULL);
INSERT INTO sys_menu VALUES (2504, 250, '0,1,250', '字典删除', 'B', NULL, '', NULL, 'sys:dict:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.886439', '2026-07-30 20:08:41.886439', NULL);
INSERT INTO sys_menu VALUES (2511, 251, '0,1,251', '字典项查询', 'B', NULL, '', NULL, 'sys:dict-item:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.887736', '2026-07-30 20:08:41.887736', NULL);
INSERT INTO sys_menu VALUES (3040, 3000, '0,3040', '样本库', 'M', 'AITCSample', 'samples', 'aitc/sample', NULL, NULL, 0, 1, 0, 4, 'el-icon-CreditCard', NULL, '2026-07-31 21:39:12.23725', '2026-08-10 16:48:38.577117', '[]');

-- Data for Name: sys_notice; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_notice VALUES (1, 'v3.0.0 版本发布 - 多租户功能上线', '<p>🎉 新版本发布，主要更新内容：</p><p>1. 新增多租户功能，支持租户隔离和数据管理</p><p>2. 优化系统性能，提升响应速度</p><p>3. 完善权限管理，增强安全性</p><p>4. 修复已知问题，提升系统稳定性</p>', 1, 'H', 1, NULL, 1, 1, '2024-12-15 10:00:00', NULL, 1, '2024-12-15 10:00:00', 1, '2024-12-15 10:00:00', 0);
INSERT INTO sys_notice VALUES (2, '系统维护通知 - 2024年12月20日', '<p>⏰ 系统维护通知</p><p>系统将于 <strong>2024年12月20日（本周五）凌晨 2:00-4:00</strong> 进行例行维护升级。</p><p>维护期间系统将暂停服务，请提前做好数据备份工作。</p><p>给您带来的不便，敬请谅解！</p>', 2, 'H', 1, NULL, 1, 1, '2024-12-18 14:30:00', NULL, 1, '2024-12-18 14:30:00', 1, '2024-12-18 14:30:00', 0);
INSERT INTO sys_notice VALUES (3, '安全提醒 - 防范钓鱼邮件', '<p>⚠️ 安全提醒</p><p>近期发现有不法分子通过钓鱼邮件进行网络攻击，请大家提高警惕：</p><p>1. 不要点击来源不明的邮件链接</p><p>2. 不要下载可疑附件</p><p>3. 遇到可疑邮件请及时联系IT部门</p><p>4. 定期修改密码，使用强密码策略</p>', 3, 'H', 1, NULL, 1, 1, '2024-12-10 09:00:00', NULL, 1, '2024-12-10 09:00:00', 1, '2024-12-10 09:00:00', 0);
INSERT INTO sys_notice VALUES (4, '元旦假期安排通知', '<p>📅 元旦假期安排</p><p>根据国家法定节假日安排，公司元旦假期时间为：</p><p><strong>2024年12月30日（周一）至 2025年1月1日（周三）</strong>，共3天。</p><p>2024年12月29日（周日）正常上班。</p><p>祝大家元旦快乐，假期愉快！</p>', 4, 'M', 1, NULL, 1, 1, '2024-12-25 16:00:00', NULL, 1, '2024-12-25 16:00:00', 1, '2024-12-25 16:00:00', 0);
INSERT INTO sys_notice VALUES (5, '新产品发布会邀请', '<p>🎊 新产品发布会邀请</p><p>公司将于 <strong>2025年1月15日下午14:00</strong> 在总部会议室举办新产品发布会。</p><p>届时将展示最新研发的产品和技术成果，欢迎全体员工参加。</p><p>请各部门提前安排好工作，准时参加。</p>', 5, 'M', 1, NULL, 1, 1, '2024-12-28 11:00:00', NULL, 1, '2024-12-28 11:00:00', 1, '2024-12-28 11:00:00', 0);
INSERT INTO sys_notice VALUES (6, 'v2.16.1 版本更新', '<p>✨ 版本更新</p><p>v2.16.1 版本已发布，主要修复内容：</p><p>1. 修复 WebSocket 重复连接导致的后台线程阻塞问题</p><p>2. 优化通知公告功能，提升用户体验</p><p>3. 修复部分已知bug</p><p>建议尽快更新到最新版本。</p>', 1, 'M', 1, NULL, 1, 1, '2024-12-05 15:30:00', NULL, 1, '2024-12-05 15:30:00', 1, '2024-12-05 15:30:00', 0);
INSERT INTO sys_notice VALUES (7, '年终总结会议通知', '<p>📋 年终总结会议通知</p><p>各部门年终总结会议将于 <strong>2024年12月30日上午9:00</strong> 召开。</p><p>请各部门负责人提前准备好年度工作总结和下年度工作计划。</p><p>会议地点：总部大会议室</p>', 5, 'M', 2, '1,2', 1, 1, '2024-12-22 10:00:00', NULL, 1, '2024-12-22 10:00:00', 1, '2024-12-22 10:00:00', 0);
INSERT INTO sys_notice VALUES (8, '系统功能优化完成', '<p>✅ 系统功能优化</p><p>已完成以下功能优化：</p><p>1. 优化用户管理界面，提升操作体验</p><p>2. 增强数据导出功能，支持更多格式</p><p>3. 优化搜索功能，提升查询效率</p><p>4. 修复部分界面显示问题</p>', 1, 'L', 1, NULL, 1, 1, '2024-12-12 14:20:00', NULL, 1, '2024-12-12 14:20:00', 1, '2024-12-12 14:20:00', 0);
INSERT INTO sys_notice VALUES (9, '员工培训计划', '<p>📚 员工培训计划</p><p>为提升员工专业技能，公司将于 <strong>2025年1月8日-10日</strong> 组织技术培训。</p><p>培训内容：</p><p>1. 新技术框架应用</p><p>2. 代码规范与最佳实践</p><p>3. 系统架构设计</p><p>请各部门合理安排工作，确保培训顺利进行。</p>', 5, 'M', 1, NULL, 1, 1, '2024-12-20 09:30:00', NULL, 1, '2024-12-20 09:30:00', 1, '2024-12-20 09:30:00', 0);
INSERT INTO sys_notice VALUES (10, '数据备份提醒', '<p>💾 数据备份提醒</p><p>请各部门注意定期备份重要数据，建议每周至少备份一次。</p><p>备份方式：</p><p>1. 使用系统自带备份功能</p><p>2. 手动导出重要数据</p><p>3. 联系IT部门协助备份</p><p>数据安全，人人有责！</p>', 3, 'L', 1, NULL, 1, 1, '2024-12-08 08:00:00', NULL, 1, '2024-12-08 08:00:00', 1, '2024-12-08 08:00:00', 0);

-- Data for Name: sys_role; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_role VALUES (1, '超级管理员', 'ROOT', 1, 1, 1, NULL, '2026-07-30 20:08:41.930657', NULL, '2026-07-30 20:08:41.930657', 0);
INSERT INTO sys_role VALUES (2, '系统管理员', 'ADMIN', 2, 1, 1, NULL, '2026-07-30 20:08:41.931815', NULL, NULL, 0);
INSERT INTO sys_role VALUES (3, '访问游客', 'GUEST', 3, 1, 3, NULL, '2026-07-30 20:08:41.932563', NULL, '2026-07-30 20:08:41.932563', 0);
INSERT INTO sys_role VALUES (4, '部门主管', 'DEPT_MANAGER', 4, 1, 2, NULL, '2026-07-30 20:08:41.933173', NULL, '2026-07-30 20:08:41.933173', 0);
INSERT INTO sys_role VALUES (5, '部门成员', 'DEPT_MEMBER', 5, 1, 3, NULL, '2026-07-30 20:08:41.933789', NULL, '2026-07-30 20:08:41.933789', 0);
INSERT INTO sys_role VALUES (6, '普通员工', 'EMPLOYEE', 6, 1, 4, NULL, '2026-07-30 20:08:41.934415', NULL, '2026-07-30 20:08:41.934415', 0);
INSERT INTO sys_role VALUES (7, '自定义权限用户', 'CUSTOM_USER', 7, 1, 5, NULL, '2026-07-30 20:08:41.935091', NULL, '2026-07-30 20:08:41.935091', 0);

-- Data for Name: sys_role_dept; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_role_dept VALUES (7, 1);
INSERT INTO sys_role_dept VALUES (7, 2);

-- Data for Name: sys_role_menu; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_role_menu VALUES (2, 1);
INSERT INTO sys_role_menu VALUES (2, 210);
INSERT INTO sys_role_menu VALUES (2, 2101);
INSERT INTO sys_role_menu VALUES (2, 2102);
INSERT INTO sys_role_menu VALUES (2, 2103);
INSERT INTO sys_role_menu VALUES (2, 2104);
INSERT INTO sys_role_menu VALUES (2, 2105);
INSERT INTO sys_role_menu VALUES (2, 2106);
INSERT INTO sys_role_menu VALUES (2, 2107);
INSERT INTO sys_role_menu VALUES (2, 220);
INSERT INTO sys_role_menu VALUES (2, 2201);
INSERT INTO sys_role_menu VALUES (2, 2202);
INSERT INTO sys_role_menu VALUES (2, 2203);
INSERT INTO sys_role_menu VALUES (2, 2204);
INSERT INTO sys_role_menu VALUES (2, 2205);
INSERT INTO sys_role_menu VALUES (2, 230);
INSERT INTO sys_role_menu VALUES (2, 2301);
INSERT INTO sys_role_menu VALUES (2, 2302);
INSERT INTO sys_role_menu VALUES (2, 2303);
INSERT INTO sys_role_menu VALUES (2, 2304);
INSERT INTO sys_role_menu VALUES (2, 240);
INSERT INTO sys_role_menu VALUES (2, 2401);
INSERT INTO sys_role_menu VALUES (2, 2402);
INSERT INTO sys_role_menu VALUES (2, 2403);
INSERT INTO sys_role_menu VALUES (2, 2404);
INSERT INTO sys_role_menu VALUES (2, 250);
INSERT INTO sys_role_menu VALUES (2, 2501);
INSERT INTO sys_role_menu VALUES (2, 2502);
INSERT INTO sys_role_menu VALUES (2, 2503);
INSERT INTO sys_role_menu VALUES (2, 2504);
INSERT INTO sys_role_menu VALUES (2, 251);
INSERT INTO sys_role_menu VALUES (2, 2511);
INSERT INTO sys_role_menu VALUES (2, 2512);
INSERT INTO sys_role_menu VALUES (2, 2513);
INSERT INTO sys_role_menu VALUES (2, 2514);
INSERT INTO sys_role_menu VALUES (2, 260);
INSERT INTO sys_role_menu VALUES (2, 2601);
INSERT INTO sys_role_menu VALUES (2, 270);
INSERT INTO sys_role_menu VALUES (2, 2701);
INSERT INTO sys_role_menu VALUES (2, 2702);
INSERT INTO sys_role_menu VALUES (2, 2703);
INSERT INTO sys_role_menu VALUES (2, 2704);
INSERT INTO sys_role_menu VALUES (2, 2705);
INSERT INTO sys_role_menu VALUES (2, 280);
INSERT INTO sys_role_menu VALUES (2, 2801);
INSERT INTO sys_role_menu VALUES (2, 2802);
INSERT INTO sys_role_menu VALUES (2, 2803);
INSERT INTO sys_role_menu VALUES (2, 2804);
INSERT INTO sys_role_menu VALUES (2, 2805);
INSERT INTO sys_role_menu VALUES (2, 2806);
INSERT INTO sys_role_menu VALUES (7, 1);
INSERT INTO sys_role_menu VALUES (7, 210);
INSERT INTO sys_role_menu VALUES (7, 2101);
INSERT INTO sys_role_menu VALUES (7, 2102);
INSERT INTO sys_role_menu VALUES (7, 2103);
INSERT INTO sys_role_menu VALUES (7, 2104);
INSERT INTO sys_role_menu VALUES (7, 2105);
INSERT INTO sys_role_menu VALUES (7, 2106);
INSERT INTO sys_role_menu VALUES (7, 2107);
INSERT INTO sys_role_menu VALUES (7, 220);
INSERT INTO sys_role_menu VALUES (7, 2201);
INSERT INTO sys_role_menu VALUES (7, 2202);
INSERT INTO sys_role_menu VALUES (7, 2203);
INSERT INTO sys_role_menu VALUES (7, 2204);
INSERT INTO sys_role_menu VALUES (7, 2205);
INSERT INTO sys_role_menu VALUES (2, 3000);
INSERT INTO sys_role_menu VALUES (2, 3010);
INSERT INTO sys_role_menu VALUES (2, 3011);
INSERT INTO sys_role_menu VALUES (2, 3012);
INSERT INTO sys_role_menu VALUES (2, 3013);
INSERT INTO sys_role_menu VALUES (2, 3014);
INSERT INTO sys_role_menu VALUES (2, 3015);
INSERT INTO sys_role_menu VALUES (2, 3016);
INSERT INTO sys_role_menu VALUES (2, 3017);
INSERT INTO sys_role_menu VALUES (2, 3018);
INSERT INTO sys_role_menu VALUES (2, 3019);
INSERT INTO sys_role_menu VALUES (2, 3020);
INSERT INTO sys_role_menu VALUES (2, 3021);
INSERT INTO sys_role_menu VALUES (2, 3022);
INSERT INTO sys_role_menu VALUES (2, 3023);
INSERT INTO sys_role_menu VALUES (2, 3030);
INSERT INTO sys_role_menu VALUES (2, 3031);
INSERT INTO sys_role_menu VALUES (2, 3032);
INSERT INTO sys_role_menu VALUES (2, 3033);
INSERT INTO sys_role_menu VALUES (2, 3034);
INSERT INTO sys_role_menu VALUES (2, 3040);
INSERT INTO sys_role_menu VALUES (2, 3041);
INSERT INTO sys_role_menu VALUES (2, 3042);
INSERT INTO sys_role_menu VALUES (2, 3043);
INSERT INTO sys_role_menu VALUES (2, 3044);
INSERT INTO sys_role_menu VALUES (2, 3060);
INSERT INTO sys_role_menu VALUES (2, 3070);
INSERT INTO sys_role_menu VALUES (2, 3071);
INSERT INTO sys_role_menu VALUES (2, 3072);
INSERT INTO sys_role_menu VALUES (1, 3000);
INSERT INTO sys_role_menu VALUES (1, 3010);
INSERT INTO sys_role_menu VALUES (1, 3011);
INSERT INTO sys_role_menu VALUES (1, 3012);
INSERT INTO sys_role_menu VALUES (1, 3013);
INSERT INTO sys_role_menu VALUES (1, 3014);
INSERT INTO sys_role_menu VALUES (1, 3015);
INSERT INTO sys_role_menu VALUES (1, 3016);
INSERT INTO sys_role_menu VALUES (1, 3017);
INSERT INTO sys_role_menu VALUES (1, 3018);
INSERT INTO sys_role_menu VALUES (1, 3019);
INSERT INTO sys_role_menu VALUES (1, 3020);
INSERT INTO sys_role_menu VALUES (1, 3021);
INSERT INTO sys_role_menu VALUES (1, 3022);
INSERT INTO sys_role_menu VALUES (1, 3023);
INSERT INTO sys_role_menu VALUES (1, 3030);
INSERT INTO sys_role_menu VALUES (1, 3031);
INSERT INTO sys_role_menu VALUES (1, 3032);
INSERT INTO sys_role_menu VALUES (1, 3033);
INSERT INTO sys_role_menu VALUES (1, 3034);
INSERT INTO sys_role_menu VALUES (1, 3040);
INSERT INTO sys_role_menu VALUES (1, 3041);
INSERT INTO sys_role_menu VALUES (1, 3042);
INSERT INTO sys_role_menu VALUES (1, 3043);
INSERT INTO sys_role_menu VALUES (1, 3044);
INSERT INTO sys_role_menu VALUES (1, 3060);
INSERT INTO sys_role_menu VALUES (1, 3070);
INSERT INTO sys_role_menu VALUES (1, 3071);
INSERT INTO sys_role_menu VALUES (1, 3072);
INSERT INTO sys_role_menu VALUES (1, 3080);
INSERT INTO sys_role_menu VALUES (2, 3080);
INSERT INTO sys_role_menu VALUES (1, 3081);
INSERT INTO sys_role_menu VALUES (2, 3081);
INSERT INTO sys_role_menu VALUES (1, 3082);
INSERT INTO sys_role_menu VALUES (2, 3082);
INSERT INTO sys_role_menu VALUES (1, 3083);
INSERT INTO sys_role_menu VALUES (2, 3083);
INSERT INTO sys_role_menu VALUES (1, 3084);
INSERT INTO sys_role_menu VALUES (2, 3084);
INSERT INTO sys_role_menu VALUES (1, 3024);
INSERT INTO sys_role_menu VALUES (2, 3024);
INSERT INTO sys_role_menu VALUES (1, 3025);
INSERT INTO sys_role_menu VALUES (2, 3025);
INSERT INTO sys_role_menu VALUES (6, 3000);
INSERT INTO sys_role_menu VALUES (6, 3010);
INSERT INTO sys_role_menu VALUES (6, 3011);
INSERT INTO sys_role_menu VALUES (6, 3012);
INSERT INTO sys_role_menu VALUES (6, 3013);
INSERT INTO sys_role_menu VALUES (6, 3014);
INSERT INTO sys_role_menu VALUES (6, 3015);
INSERT INTO sys_role_menu VALUES (6, 3016);
INSERT INTO sys_role_menu VALUES (6, 3017);
INSERT INTO sys_role_menu VALUES (6, 3018);
INSERT INTO sys_role_menu VALUES (6, 3019);
INSERT INTO sys_role_menu VALUES (6, 3024);
INSERT INTO sys_role_menu VALUES (6, 3020);
INSERT INTO sys_role_menu VALUES (6, 3021);
INSERT INTO sys_role_menu VALUES (6, 3022);
INSERT INTO sys_role_menu VALUES (6, 3023);
INSERT INTO sys_role_menu VALUES (6, 3025);
INSERT INTO sys_role_menu VALUES (6, 3040);
INSERT INTO sys_role_menu VALUES (6, 3041);
INSERT INTO sys_role_menu VALUES (6, 3042);
INSERT INTO sys_role_menu VALUES (6, 3043);
INSERT INTO sys_role_menu VALUES (6, 3044);
INSERT INTO sys_role_menu VALUES (6, 3060);
INSERT INTO sys_role_menu VALUES (6, 3070);
INSERT INTO sys_role_menu VALUES (6, 3071);
INSERT INTO sys_role_menu VALUES (6, 3072);
INSERT INTO sys_role_menu VALUES (6, 3080);
INSERT INTO sys_role_menu VALUES (6, 3081);
INSERT INTO sys_role_menu VALUES (6, 3082);
INSERT INTO sys_role_menu VALUES (6, 3083);
INSERT INTO sys_role_menu VALUES (6, 3084);
INSERT INTO sys_role_menu VALUES (6, 1);
INSERT INTO sys_role_menu VALUES (6, 210);
INSERT INTO sys_role_menu VALUES (6, 2101);
INSERT INTO sys_role_menu VALUES (6, 2102);
INSERT INTO sys_role_menu VALUES (6, 2103);
INSERT INTO sys_role_menu VALUES (6, 2104);
INSERT INTO sys_role_menu VALUES (6, 2105);
INSERT INTO sys_role_menu VALUES (6, 2106);
INSERT INTO sys_role_menu VALUES (6, 2107);
INSERT INTO sys_role_menu VALUES (6, 220);
INSERT INTO sys_role_menu VALUES (6, 2201);
INSERT INTO sys_role_menu VALUES (6, 2202);
INSERT INTO sys_role_menu VALUES (6, 2203);
INSERT INTO sys_role_menu VALUES (6, 2204);
INSERT INTO sys_role_menu VALUES (6, 2205);
INSERT INTO sys_role_menu VALUES (4, 3000);
INSERT INTO sys_role_menu VALUES (4, 3010);
INSERT INTO sys_role_menu VALUES (4, 3011);
INSERT INTO sys_role_menu VALUES (4, 3012);
INSERT INTO sys_role_menu VALUES (4, 3013);
INSERT INTO sys_role_menu VALUES (4, 3014);
INSERT INTO sys_role_menu VALUES (4, 3015);
INSERT INTO sys_role_menu VALUES (4, 3016);
INSERT INTO sys_role_menu VALUES (4, 3017);
INSERT INTO sys_role_menu VALUES (4, 3018);
INSERT INTO sys_role_menu VALUES (4, 3019);
INSERT INTO sys_role_menu VALUES (4, 3024);
INSERT INTO sys_role_menu VALUES (4, 3020);
INSERT INTO sys_role_menu VALUES (4, 3021);
INSERT INTO sys_role_menu VALUES (4, 3022);
INSERT INTO sys_role_menu VALUES (4, 3023);
INSERT INTO sys_role_menu VALUES (4, 3025);
INSERT INTO sys_role_menu VALUES (4, 3040);
INSERT INTO sys_role_menu VALUES (4, 3041);
INSERT INTO sys_role_menu VALUES (4, 3042);
INSERT INTO sys_role_menu VALUES (4, 3043);
INSERT INTO sys_role_menu VALUES (4, 3044);
INSERT INTO sys_role_menu VALUES (4, 3060);
INSERT INTO sys_role_menu VALUES (4, 3070);
INSERT INTO sys_role_menu VALUES (4, 3071);
INSERT INTO sys_role_menu VALUES (4, 3072);
INSERT INTO sys_role_menu VALUES (4, 3080);
INSERT INTO sys_role_menu VALUES (4, 3081);
INSERT INTO sys_role_menu VALUES (4, 3082);
INSERT INTO sys_role_menu VALUES (4, 3083);
INSERT INTO sys_role_menu VALUES (4, 3084);
INSERT INTO sys_role_menu VALUES (4, 1);
INSERT INTO sys_role_menu VALUES (4, 210);
INSERT INTO sys_role_menu VALUES (4, 2101);
INSERT INTO sys_role_menu VALUES (4, 2102);
INSERT INTO sys_role_menu VALUES (4, 2103);
INSERT INTO sys_role_menu VALUES (4, 2104);
INSERT INTO sys_role_menu VALUES (4, 2105);
INSERT INTO sys_role_menu VALUES (4, 2106);
INSERT INTO sys_role_menu VALUES (4, 2107);
INSERT INTO sys_role_menu VALUES (4, 220);
INSERT INTO sys_role_menu VALUES (4, 2201);
INSERT INTO sys_role_menu VALUES (4, 2202);
INSERT INTO sys_role_menu VALUES (4, 2203);
INSERT INTO sys_role_menu VALUES (4, 2204);
INSERT INTO sys_role_menu VALUES (4, 2205);
INSERT INTO sys_role_menu VALUES (5, 3000);
INSERT INTO sys_role_menu VALUES (5, 3010);
INSERT INTO sys_role_menu VALUES (5, 3011);
INSERT INTO sys_role_menu VALUES (5, 3012);
INSERT INTO sys_role_menu VALUES (5, 3013);
INSERT INTO sys_role_menu VALUES (5, 3014);
INSERT INTO sys_role_menu VALUES (5, 3015);
INSERT INTO sys_role_menu VALUES (5, 3016);
INSERT INTO sys_role_menu VALUES (5, 3017);
INSERT INTO sys_role_menu VALUES (5, 3018);
INSERT INTO sys_role_menu VALUES (5, 3019);
INSERT INTO sys_role_menu VALUES (5, 3024);
INSERT INTO sys_role_menu VALUES (5, 3020);
INSERT INTO sys_role_menu VALUES (5, 3021);
INSERT INTO sys_role_menu VALUES (5, 3022);
INSERT INTO sys_role_menu VALUES (5, 3023);
INSERT INTO sys_role_menu VALUES (5, 3025);
INSERT INTO sys_role_menu VALUES (5, 3040);
INSERT INTO sys_role_menu VALUES (5, 3041);
INSERT INTO sys_role_menu VALUES (5, 3042);
INSERT INTO sys_role_menu VALUES (5, 3043);
INSERT INTO sys_role_menu VALUES (5, 3044);
INSERT INTO sys_role_menu VALUES (5, 3060);
INSERT INTO sys_role_menu VALUES (5, 3070);
INSERT INTO sys_role_menu VALUES (5, 3071);
INSERT INTO sys_role_menu VALUES (5, 3072);
INSERT INTO sys_role_menu VALUES (5, 3080);
INSERT INTO sys_role_menu VALUES (5, 3081);
INSERT INTO sys_role_menu VALUES (5, 3082);
INSERT INTO sys_role_menu VALUES (5, 3083);
INSERT INTO sys_role_menu VALUES (5, 3084);
INSERT INTO sys_role_menu VALUES (5, 1);
INSERT INTO sys_role_menu VALUES (5, 210);
INSERT INTO sys_role_menu VALUES (5, 2101);
INSERT INTO sys_role_menu VALUES (5, 2102);
INSERT INTO sys_role_menu VALUES (5, 2103);
INSERT INTO sys_role_menu VALUES (5, 2104);
INSERT INTO sys_role_menu VALUES (5, 2105);
INSERT INTO sys_role_menu VALUES (5, 2106);
INSERT INTO sys_role_menu VALUES (5, 2107);
INSERT INTO sys_role_menu VALUES (5, 220);
INSERT INTO sys_role_menu VALUES (5, 2201);
INSERT INTO sys_role_menu VALUES (5, 2202);
INSERT INTO sys_role_menu VALUES (5, 2203);
INSERT INTO sys_role_menu VALUES (5, 2204);
INSERT INTO sys_role_menu VALUES (5, 2205);

-- Data for Name: sys_user; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_user VALUES (1, 'root', '有来技术', 0, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', NULL, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345677', 1, 'youlaitech@163.com', '2026-07-30 20:08:41.984546', NULL, '2026-07-30 20:08:41.984546', NULL, 0);
INSERT INTO sys_user VALUES (2, 'admin', '系统管理员', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18888888888', 1, 'youlaitech@163.com', '2026-07-30 20:08:41.985544', NULL, '2026-07-30 20:08:41.985544', NULL, 0);
INSERT INTO sys_user VALUES (3, 'test', '测试小用户', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 3, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345679', 1, 'youlaitech@163.com', '2026-07-30 20:08:41.986213', NULL, '2026-07-30 20:08:41.986213', NULL, 0);
INSERT INTO sys_user VALUES (4, 'dept_manager', '部门主管', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345680', 1, 'manager@youlaitech.com', '2026-07-30 20:08:41.986857', NULL, '2026-07-30 20:08:41.986857', NULL, 0);
INSERT INTO sys_user VALUES (5, 'dept_member', '部门成员', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345681', 1, 'member@youlaitech.com', '2026-07-30 20:08:41.987548', NULL, '2026-07-30 20:08:41.987548', NULL, 0);
INSERT INTO sys_user VALUES (7, 'custom_user', '自定义权限用户', 2, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 3, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345683', 1, 'custom@youlaitech.com', '2026-07-30 20:08:41.9889', NULL, '2026-07-30 21:43:38.223241', 2, 0);
INSERT INTO sys_user VALUES (6, 'employee', '普通员工', 1, '$2b$12$skFqm9l6IZA4cUQ7/K/YueeCckufs1b4nWd7H4ZcgKh9cmn/Mhi4O', 2, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345682', 1, 'employee@youlaitech.com', '2026-07-30 20:08:41.988193', NULL, '2026-08-08 23:42:54.967576', NULL, 0);

-- Data for Name: sys_user_notice; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_user_notice VALUES (1, 1, 2, 1, NULL, '2026-07-30 20:08:42.110029', '2026-07-30 20:08:42.110029', 0);
INSERT INTO sys_user_notice VALUES (2, 2, 2, 1, NULL, '2026-07-30 20:08:42.110993', '2026-07-30 20:08:42.110993', 0);
INSERT INTO sys_user_notice VALUES (3, 3, 2, 1, NULL, '2026-07-30 20:08:42.111661', '2026-07-30 20:08:42.111661', 0);
INSERT INTO sys_user_notice VALUES (4, 4, 2, 1, NULL, '2026-07-30 20:08:42.112291', '2026-07-30 20:08:42.112291', 0);
INSERT INTO sys_user_notice VALUES (5, 5, 2, 1, NULL, '2026-07-30 20:08:42.112928', '2026-07-30 20:08:42.112928', 0);
INSERT INTO sys_user_notice VALUES (6, 6, 2, 1, NULL, '2026-07-30 20:08:42.113547', '2026-07-30 20:08:42.113547', 0);
INSERT INTO sys_user_notice VALUES (7, 7, 2, 1, NULL, '2026-07-30 20:08:42.11425', '2026-07-30 20:08:42.11425', 0);
INSERT INTO sys_user_notice VALUES (8, 8, 2, 1, NULL, '2026-07-30 20:08:42.115053', '2026-07-30 20:08:42.115053', 0);
INSERT INTO sys_user_notice VALUES (9, 9, 2, 1, NULL, '2026-07-30 20:08:42.115867', '2026-07-30 20:08:42.115867', 0);
INSERT INTO sys_user_notice VALUES (10, 10, 2, 1, NULL, '2026-07-30 20:08:42.116589', '2026-07-30 20:08:42.116589', 0);

-- Data for Name: sys_user_role; Type: TABLE DATA; Schema: public; Owner: -
INSERT INTO sys_user_role VALUES (1, 1);
INSERT INTO sys_user_role VALUES (2, 2);
INSERT INTO sys_user_role VALUES (3, 3);
INSERT INTO sys_user_role VALUES (4, 4);
INSERT INTO sys_user_role VALUES (5, 5);
INSERT INTO sys_user_role VALUES (6, 6);
INSERT INTO sys_user_role VALUES (7, 7);

-- Data for Name: sys_user_social; Type: TABLE DATA; Schema: public; Owner: -
-- Name: sys_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_dept_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_dict_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_dict_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_menu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_notice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_user_notice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_user_social_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -

-- ----------------------------
-- 种子数据
-- ----------------------------

INSERT INTO sys_config VALUES (1, '系统限流QPS', 'IP_QPS_THRESHOLD_LIMIT', '10', '单个IP请求的最大每秒查询数（QPS）阈值Key', '2026-07-30 20:08:42.073333', 1, NULL, NULL, 0);

INSERT INTO sys_dept VALUES (1, '有来技术', 'YOULAI', 0, '0', 1, 1, 1, NULL, 1, '2026-07-30 20:08:41.803636', 0);
INSERT INTO sys_dept VALUES (2, '研发部门', 'RD001', 1, '0,1', 1, 1, 2, NULL, 2, '2026-07-30 20:08:41.804558', 0);
INSERT INTO sys_dept VALUES (3, '测试部门', 'QA001', 1, '0,1', 1, 1, 2, NULL, 2, '2026-07-30 20:08:41.805213', 0);

INSERT INTO sys_dict VALUES (1, 'gender', '性别', 1, NULL, '2026-07-30 20:08:41.819334', 1, '2026-07-30 20:08:41.819334', 1, 0);
INSERT INTO sys_dict VALUES (2, 'notice_type', '通知类型', 1, NULL, '2026-07-30 20:08:41.820109', 1, '2026-07-30 20:08:41.820109', 1, 0);
INSERT INTO sys_dict VALUES (3, 'notice_level', '通知级别', 1, NULL, '2026-07-30 20:08:41.820713', 1, '2026-07-30 20:08:41.820713', 1, 0);

INSERT INTO sys_dict_item VALUES (1, 'gender', '1', '男', 'primary', 1, 1, NULL, '2026-07-30 20:08:41.83746', 1, '2026-07-30 20:08:41.83746', 1);
INSERT INTO sys_dict_item VALUES (2, 'gender', '2', '女', 'danger', 1, 2, NULL, '2026-07-30 20:08:41.838232', 1, '2026-07-30 20:08:41.838232', 1);
INSERT INTO sys_dict_item VALUES (3, 'gender', '0', '保密', 'info', 1, 3, NULL, '2026-07-30 20:08:41.838893', 1, '2026-07-30 20:08:41.838893', 1);
INSERT INTO sys_dict_item VALUES (4, 'notice_type', '1', '系统升级', 'success', 1, 1, '', '2026-07-30 20:08:41.839563', 1, '2026-07-30 20:08:41.839563', 1);
INSERT INTO sys_dict_item VALUES (5, 'notice_type', '2', '系统维护', 'primary', 1, 2, '', '2026-07-30 20:08:41.840185', 1, '2026-07-30 20:08:41.840185', 1);
INSERT INTO sys_dict_item VALUES (6, 'notice_type', '3', '安全警告', 'danger', 1, 3, '', '2026-07-30 20:08:41.840876', 1, '2026-07-30 20:08:41.840876', 1);
INSERT INTO sys_dict_item VALUES (7, 'notice_type', '4', '假期通知', 'success', 1, 4, '', '2026-07-30 20:08:41.841477', 1, '2026-07-30 20:08:41.841477', 1);
INSERT INTO sys_dict_item VALUES (8, 'notice_type', '5', '公司新闻', 'primary', 1, 5, '', '2026-07-30 20:08:41.842102', 1, '2026-07-30 20:08:41.842102', 1);
INSERT INTO sys_dict_item VALUES (9, 'notice_type', '99', '其他', 'info', 1, 99, '', '2026-07-30 20:08:41.842708', 1, '2026-07-30 20:08:41.842708', 1);
INSERT INTO sys_dict_item VALUES (10, 'notice_level', 'L', '低', 'info', 1, 1, '', '2026-07-30 20:08:41.843334', 1, '2026-07-30 20:08:41.843334', 1);
INSERT INTO sys_dict_item VALUES (11, 'notice_level', 'M', '中', 'warning', 1, 2, '', '2026-07-30 20:08:41.843919', 1, '2026-07-30 20:08:41.843919', 1);
INSERT INTO sys_dict_item VALUES (12, 'notice_level', 'H', '高', 'danger', 1, 3, '', '2026-07-30 20:08:41.844519', 1, '2026-07-30 20:08:41.844519', 1);

INSERT INTO sys_menu VALUES (3020, 3000, '0,3000', '任务管理', 'M', 'AITCTask', 'tasks', 'aitc/task', NULL, NULL, 0, 1, 1, 2, 'el-icon-Collection', NULL, '2026-07-31 21:39:12.23725', '2026-08-01 23:19:03.112315', '[]');
INSERT INTO sys_menu VALUES (3080, 3000, '0,3000', '规范管理', 'M', 'AITCSpec', 'specs', 'aitc/spec', 'aitc:spec:list', NULL, 0, 1, 1, 8, 'document', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3081, 3080, '0,3000,3080', '规范查询', 'B', NULL, '', NULL, 'aitc:spec:list', NULL, 0, 0, 1, 1, '', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3082, 3080, '0,3000,3080', '规范创建', 'B', NULL, '', NULL, 'aitc:spec:create', NULL, 0, 0, 1, 2, '', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3083, 3080, '0,3000,3080', '规范编辑', 'B', NULL, '', NULL, 'aitc:spec:update', NULL, 0, 0, 1, 3, '', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3084, 3080, '0,3000,3080', '规范删除', 'B', NULL, '', NULL, 'aitc:spec:delete', NULL, 0, 0, 1, 4, '', '', '2026-08-01 10:52:52.561991', '2026-08-01 10:52:52.561991', NULL);
INSERT INTO sys_menu VALUES (3074, 1, '0,3074', 'AI日志', 'M', 'LlmLog', 'llm-log', 'system/llm-log/index', 'sys:llm-log:list', NULL, 0, 0, 1, 99, 'monitor', NULL, NULL, '2026-08-05 23:40:10.597986', NULL);
INSERT INTO sys_menu VALUES (3000, 0, '0', '工作区', 'C', NULL, '/aitc', 'Layout', NULL, NULL, 0, 0, 1, 2, 'el-icon-Box', '', '2026-07-31 21:39:12.23725', '2026-08-08 16:49:41.165628', '[]');
INSERT INTO sys_menu VALUES (3010, 3000, '0,3010', '用例管理', 'M', 'AITCCases', 'cases', 'aitc/case', NULL, NULL, 0, 1, 1, 1, 'el-icon-List', NULL, '2026-07-31 21:39:12.23725', '2026-08-08 16:51:23.795179', '[]');
INSERT INTO sys_menu VALUES (3025, 3020, '0,3000,3020', '停止任务', 'B', NULL, '', NULL, 'aitc:task:stop', NULL, 0, 0, 1, 4, '', NULL, '2026-08-08 22:50:41.975839', '2026-08-08 22:50:41.975839', NULL);
INSERT INTO sys_menu VALUES (3011, 3010, '0,3000,3010', '用例查询', 'B', NULL, '', NULL, 'aitc:case:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3012, 3010, '0,3000,3010', '用例导入', 'B', NULL, '', NULL, 'aitc:case:import', NULL, 0, 0, 1, 2, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3013, 3010, '0,3000,3010', '用例编辑', 'B', NULL, '', NULL, 'aitc:case:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3014, 3010, '0,3000,3010', '用例删除', 'B', NULL, '', NULL, 'aitc:case:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3015, 3010, '0,3000,3010', '标记核心', 'B', NULL, '', NULL, 'aitc:case:core', NULL, 0, 0, 1, 5, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (251, 1, '0,1', '字典项', 'M', 'DictItem', 'dict-item', 'system/dict/dict-item', NULL, NULL, 0, 1, 1, 6, '', NULL, '2026-07-30 20:08:41.887077', '2026-07-30 20:08:41.887077', NULL);
INSERT INTO sys_menu VALUES (260, 1, '0,1', '系统日志', 'M', 'Log', 'log', 'system/log/index', NULL, NULL, 0, 1, 1, 7, 'document', NULL, '2026-07-30 20:08:41.890096', '2026-07-30 20:08:41.890096', NULL);
INSERT INTO sys_menu VALUES (270, 1, '0,1', '系统配置', 'M', 'Config', 'config', 'system/config/index', NULL, NULL, 0, 1, 1, 8, 'setting', NULL, '2026-07-30 20:08:41.891272', '2026-07-30 20:08:41.891272', NULL);
INSERT INTO sys_menu VALUES (2701, 270, '0,1,270', '系统配置查询', 'B', NULL, '', NULL, 'sys:config:list', NULL, 0, 1, 1, 1, '', NULL, '2026-07-30 20:08:41.89193', '2026-07-30 20:08:41.89193', NULL);
INSERT INTO sys_menu VALUES (2702, 270, '0,1,270', '系统配置新增', 'B', NULL, '', NULL, 'sys:config:create', NULL, 0, 1, 1, 2, '', NULL, '2026-07-30 20:08:41.892537', '2026-07-30 20:08:41.892537', NULL);
INSERT INTO sys_menu VALUES (2703, 270, '0,1,270', '系统配置修改', 'B', NULL, '', NULL, 'sys:config:update', NULL, 0, 1, 1, 3, '', NULL, '2026-07-30 20:08:41.893122', '2026-07-30 20:08:41.893122', NULL);
INSERT INTO sys_menu VALUES (2704, 270, '0,1,270', '系统配置删除', 'B', NULL, '', NULL, 'sys:config:delete', NULL, 0, 1, 1, 4, '', NULL, '2026-07-30 20:08:41.893745', '2026-07-30 20:08:41.893745', NULL);
INSERT INTO sys_menu VALUES (2705, 270, '0,1,270', '系统配置刷新', 'B', NULL, '', NULL, 'sys:config:refresh', NULL, 0, 1, 1, 5, '', NULL, '2026-07-30 20:08:41.894378', '2026-07-30 20:08:41.894378', NULL);
INSERT INTO sys_menu VALUES (2805, 280, '0,1,280', '通知发布', 'B', NULL, '', NULL, 'sys:notice:publish', NULL, 0, 1, 1, 5, '', NULL, '2026-07-30 20:08:41.898156', '2026-07-30 20:08:41.898156', NULL);
INSERT INTO sys_menu VALUES (2806, 280, '0,1,280', '通知撤回', 'B', NULL, '', NULL, 'sys:notice:revoke', NULL, 0, 1, 1, 6, '', NULL, '2026-07-30 20:08:41.898891', '2026-07-30 20:08:41.898891', NULL);
INSERT INTO sys_menu VALUES (3016, 3010, '0,3000,3010', '项目查询', 'B', NULL, '', NULL, 'aitc:project:list', NULL, 0, 0, 1, 6, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (1, 0, '0', '系统管理', 'C', NULL, '/system', 'Layout', NULL, NULL, 0, 0, 1, 2, 'system', '/system/user', '2026-07-30 20:08:41.862986', '2026-07-30 22:26:18.116852', '[]');
INSERT INTO sys_menu VALUES (220, 1, '0,1', '角色管理', 'M', 'Role', 'role', 'system/role/index', NULL, NULL, 0, 1, 1, 2, 'role', NULL, '2026-07-30 20:08:41.873884', '2026-07-30 20:08:41.873884', NULL);
INSERT INTO sys_menu VALUES (3060, 3000, '0,3000', '用例审核', 'M', 'CaseReviewIndex', 'review', 'aitc/task/case-review-index', NULL, NULL, 0, 1, 0, 6, 'gitcode', NULL, '2026-07-31 21:39:12.23725', '2026-08-05 00:40:25.548695', '[]');
INSERT INTO sys_menu VALUES (3024, 3010, '0,3000,3010', '标记样本', 'B', NULL, '', NULL, 'aitc:case:sample', NULL, 0, 0, 1, 10, '', NULL, '2026-08-02 14:42:51.28289', '2026-08-02 14:42:51.28289', NULL);
INSERT INTO sys_menu VALUES (210, 1, '0,1', '用户管理', 'M', 'User', 'user', 'system/user/index', NULL, NULL, 0, 1, 1, 1, 'el-icon-User', NULL, '2026-07-30 20:08:41.868853', '2026-07-30 20:08:41.868853', NULL);
INSERT INTO sys_menu VALUES (230, 1, '0,1', '菜单管理', 'M', 'SysMenu', 'menu', 'system/menu/index', NULL, NULL, 0, 1, 1, 3, 'menu', NULL, '2026-07-30 20:08:41.877478', '2026-07-30 20:08:41.877478', NULL);
INSERT INTO sys_menu VALUES (240, 1, '0,1', '部门管理', 'M', 'Dept', 'dept', 'system/dept/index', NULL, NULL, 0, 1, 1, 4, 'tree', NULL, '2026-07-30 20:08:41.880583', '2026-07-30 20:08:41.880583', NULL);
INSERT INTO sys_menu VALUES (250, 1, '0,1', '字典管理', 'M', 'Dict', 'dict', 'system/dict/index', NULL, NULL, 0, 1, 1, 5, 'dict', NULL, '2026-07-30 20:08:41.883995', '2026-07-30 20:08:41.883995', NULL);
INSERT INTO sys_menu VALUES (3071, 3070, '0,3000,3070', '脚本查询', 'B', NULL, '', NULL, 'aitc:script:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (2104, 210, '0,1,210', '用户删除', 'B', NULL, '', NULL, 'sys:user:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.871482', '2026-07-30 20:08:41.871482', NULL);
INSERT INTO sys_menu VALUES (2105, 210, '0,1,210', '重置密码', 'B', NULL, '', NULL, 'sys:user:reset-password', NULL, 0, 0, 1, 5, '', NULL, '2026-07-30 20:08:41.872076', '2026-07-30 20:08:41.872076', NULL);
INSERT INTO sys_menu VALUES (3072, 3070, '0,3000,3070', '脚本编辑', 'B', NULL, '', NULL, 'aitc:script:update', NULL, 0, 0, 1, 2, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3041, 3040, '0,3000,3040', '样本查询', 'B', NULL, '', NULL, 'aitc:sample:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3042, 3040, '0,3000,3040', '样本创建', 'B', NULL, '', NULL, 'aitc:sample:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3043, 3040, '0,3000,3040', '样本编辑', 'B', NULL, '', NULL, 'aitc:sample:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3044, 3040, '0,3000,3040', '样本删除', 'B', NULL, '', NULL, 'aitc:sample:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (2106, 210, '0,1,210', '用户导入', 'B', NULL, '', NULL, 'sys:user:import', NULL, 0, 0, 1, 6, '', NULL, '2026-07-30 20:08:41.872671', '2026-07-30 20:08:41.872671', NULL);
INSERT INTO sys_menu VALUES (2107, 210, '0,1,210', '用户导出', 'B', NULL, '', NULL, 'sys:user:export', NULL, 0, 0, 1, 7, '', NULL, '2026-07-30 20:08:41.873263', '2026-07-30 20:08:41.873263', NULL);
INSERT INTO sys_menu VALUES (2201, 220, '0,1,220', '角色查询', 'B', NULL, '', NULL, 'sys:role:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.874462', '2026-07-30 20:08:41.874462', NULL);
INSERT INTO sys_menu VALUES (2202, 220, '0,1,220', '角色新增', 'B', NULL, '', NULL, 'sys:role:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.875102', '2026-07-30 20:08:41.875102', NULL);
INSERT INTO sys_menu VALUES (2203, 220, '0,1,220', '角色编辑', 'B', NULL, '', NULL, 'sys:role:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.875692', '2026-07-30 20:08:41.875692', NULL);
INSERT INTO sys_menu VALUES (2204, 220, '0,1,220', '角色删除', 'B', NULL, '', NULL, 'sys:role:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.876291', '2026-07-30 20:08:41.876291', NULL);
INSERT INTO sys_menu VALUES (2512, 251, '0,1,251', '字典项新增', 'B', NULL, '', NULL, 'sys:dict-item:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.888326', '2026-07-30 20:08:41.888326', NULL);
INSERT INTO sys_menu VALUES (2513, 251, '0,1,251', '字典项编辑', 'B', NULL, '', NULL, 'sys:dict-item:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.888919', '2026-07-30 20:08:41.888919', NULL);
INSERT INTO sys_menu VALUES (2514, 251, '0,1,251', '字典项删除', 'B', NULL, '', NULL, 'sys:dict-item:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.889517', '2026-07-30 20:08:41.889517', NULL);
INSERT INTO sys_menu VALUES (2601, 260, '0,1,260', '日志查询', 'B', NULL, '', NULL, 'sys:log:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.890674', '2026-07-30 20:08:41.890674', NULL);
INSERT INTO sys_menu VALUES (280, 1, '0,1', '通知公告', 'M', 'Notice', 'notice', 'system/notice/index', NULL, NULL, 0, 0, 1, 9, '', NULL, '2026-07-30 20:08:41.895021', '2026-07-30 20:08:41.895021', NULL);
INSERT INTO sys_menu VALUES (2801, 280, '0,1,280', '通知查询', 'B', NULL, '', NULL, 'sys:notice:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.895612', '2026-07-30 20:08:41.895612', NULL);
INSERT INTO sys_menu VALUES (2802, 280, '0,1,280', '通知新增', 'B', NULL, '', NULL, 'sys:notice:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.896196', '2026-07-30 20:08:41.896196', NULL);
INSERT INTO sys_menu VALUES (2803, 280, '0,1,280', '通知编辑', 'B', NULL, '', NULL, 'sys:notice:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.896765', '2026-07-30 20:08:41.896765', NULL);
INSERT INTO sys_menu VALUES (2804, 280, '0,1,280', '通知删除', 'B', NULL, '', NULL, 'sys:notice:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.897406', '2026-07-30 20:08:41.897406', NULL);
INSERT INTO sys_menu VALUES (3017, 3010, '0,3000,3010', '项目创建', 'B', NULL, '', NULL, 'aitc:project:create', NULL, 0, 0, 1, 7, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3018, 3010, '0,3000,3010', '项目编辑', 'B', NULL, '', NULL, 'aitc:project:update', NULL, 0, 0, 1, 8, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3019, 3010, '0,3000,3010', '项目删除', 'B', NULL, '', NULL, 'aitc:project:delete', NULL, 0, 0, 1, 9, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3021, 3020, '0,3000,3020', '任务查询', 'B', NULL, '', NULL, 'aitc:task:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3022, 3020, '0,3000,3020', '创建任务', 'B', NULL, '', NULL, 'aitc:task:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3023, 3020, '0,3000,3020', '确认任务', 'B', NULL, '', NULL, 'aitc:task:confirm', NULL, 0, 0, 1, 3, '', NULL, '2026-07-31 21:39:12.23725', '2026-07-31 21:39:12.23725', NULL);
INSERT INTO sys_menu VALUES (3070, 3000, '0,3070', '脚本库', 'M', 'AITCScript', 'scripts', 'aitc/script', NULL, NULL, 0, 1, 0, 7, 'code', NULL, '2026-07-31 21:39:12.23725', '2026-08-10 16:48:48.186533', '[]');
INSERT INTO sys_menu VALUES (2101, 210, '0,1,210', '用户查询', 'B', NULL, '', NULL, 'sys:user:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.869499', '2026-07-30 20:08:41.869499', NULL);
INSERT INTO sys_menu VALUES (2102, 210, '0,1,210', '用户新增', 'B', NULL, '', NULL, 'sys:user:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.870208', '2026-07-30 20:08:41.870208', NULL);
INSERT INTO sys_menu VALUES (2103, 210, '0,1,210', '用户编辑', 'B', NULL, '', NULL, 'sys:user:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.870855', '2026-07-30 20:08:41.870855', NULL);
INSERT INTO sys_menu VALUES (2205, 220, '0,1,220', '角色分配权限', 'B', NULL, '', NULL, 'sys:role:assign', NULL, 0, 0, 1, 5, '', NULL, '2026-07-30 20:08:41.876884', '2026-07-30 20:08:41.876884', NULL);
INSERT INTO sys_menu VALUES (2301, 230, '0,1,230', '菜单查询', 'B', NULL, '', NULL, 'sys:menu:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.878089', '2026-07-30 20:08:41.878089', NULL);
INSERT INTO sys_menu VALUES (2302, 230, '0,1,230', '菜单新增', 'B', NULL, '', NULL, 'sys:menu:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.878692', '2026-07-30 20:08:41.878692', NULL);
INSERT INTO sys_menu VALUES (2303, 230, '0,1,230', '菜单编辑', 'B', NULL, '', NULL, 'sys:menu:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.879343', '2026-07-30 20:08:41.879343', NULL);
INSERT INTO sys_menu VALUES (2304, 230, '0,1,230', '菜单删除', 'B', NULL, '', NULL, 'sys:menu:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.879947', '2026-07-30 20:08:41.879947', NULL);
INSERT INTO sys_menu VALUES (2401, 240, '0,1,240', '部门查询', 'B', NULL, '', NULL, 'sys:dept:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.881354', '2026-07-30 20:08:41.881354', NULL);
INSERT INTO sys_menu VALUES (2402, 240, '0,1,240', '部门新增', 'B', NULL, '', NULL, 'sys:dept:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.882085', '2026-07-30 20:08:41.882085', NULL);
INSERT INTO sys_menu VALUES (2403, 240, '0,1,240', '部门编辑', 'B', NULL, '', NULL, 'sys:dept:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.882734', '2026-07-30 20:08:41.882734', NULL);
INSERT INTO sys_menu VALUES (2404, 240, '0,1,240', '部门删除', 'B', NULL, '', NULL, 'sys:dept:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.88336', '2026-07-30 20:08:41.88336', NULL);
INSERT INTO sys_menu VALUES (2501, 250, '0,1,250', '字典查询', 'B', NULL, '', NULL, 'sys:dict:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.884631', '2026-07-30 20:08:41.884631', NULL);
INSERT INTO sys_menu VALUES (2502, 250, '0,1,250', '字典新增', 'B', NULL, '', NULL, 'sys:dict:create', NULL, 0, 0, 1, 2, '', NULL, '2026-07-30 20:08:41.885251', '2026-07-30 20:08:41.885251', NULL);
INSERT INTO sys_menu VALUES (2503, 250, '0,1,250', '字典编辑', 'B', NULL, '', NULL, 'sys:dict:update', NULL, 0, 0, 1, 3, '', NULL, '2026-07-30 20:08:41.88585', '2026-07-30 20:08:41.88585', NULL);
INSERT INTO sys_menu VALUES (2504, 250, '0,1,250', '字典删除', 'B', NULL, '', NULL, 'sys:dict:delete', NULL, 0, 0, 1, 4, '', NULL, '2026-07-30 20:08:41.886439', '2026-07-30 20:08:41.886439', NULL);
INSERT INTO sys_menu VALUES (2511, 251, '0,1,251', '字典项查询', 'B', NULL, '', NULL, 'sys:dict-item:list', NULL, 0, 0, 1, 1, '', NULL, '2026-07-30 20:08:41.887736', '2026-07-30 20:08:41.887736', NULL);
INSERT INTO sys_menu VALUES (3040, 3000, '0,3040', '样本库', 'M', 'AITCSample', 'samples', 'aitc/sample', NULL, NULL, 0, 1, 0, 4, 'el-icon-CreditCard', NULL, '2026-07-31 21:39:12.23725', '2026-08-10 16:48:38.577117', '[]');

INSERT INTO sys_notice VALUES (1, 'v3.0.0 版本发布 - 多租户功能上线', '<p>🎉 新版本发布，主要更新内容：</p><p>1. 新增多租户功能，支持租户隔离和数据管理</p><p>2. 优化系统性能，提升响应速度</p><p>3. 完善权限管理，增强安全性</p><p>4. 修复已知问题，提升系统稳定性</p>', 1, 'H', 1, NULL, 1, 1, '2024-12-15 10:00:00', NULL, 1, '2024-12-15 10:00:00', 1, '2024-12-15 10:00:00', 0);
INSERT INTO sys_notice VALUES (2, '系统维护通知 - 2024年12月20日', '<p>⏰ 系统维护通知</p><p>系统将于 <strong>2024年12月20日（本周五）凌晨 2:00-4:00</strong> 进行例行维护升级。</p><p>维护期间系统将暂停服务，请提前做好数据备份工作。</p><p>给您带来的不便，敬请谅解！</p>', 2, 'H', 1, NULL, 1, 1, '2024-12-18 14:30:00', NULL, 1, '2024-12-18 14:30:00', 1, '2024-12-18 14:30:00', 0);
INSERT INTO sys_notice VALUES (3, '安全提醒 - 防范钓鱼邮件', '<p>⚠️ 安全提醒</p><p>近期发现有不法分子通过钓鱼邮件进行网络攻击，请大家提高警惕：</p><p>1. 不要点击来源不明的邮件链接</p><p>2. 不要下载可疑附件</p><p>3. 遇到可疑邮件请及时联系IT部门</p><p>4. 定期修改密码，使用强密码策略</p>', 3, 'H', 1, NULL, 1, 1, '2024-12-10 09:00:00', NULL, 1, '2024-12-10 09:00:00', 1, '2024-12-10 09:00:00', 0);
INSERT INTO sys_notice VALUES (4, '元旦假期安排通知', '<p>📅 元旦假期安排</p><p>根据国家法定节假日安排，公司元旦假期时间为：</p><p><strong>2024年12月30日（周一）至 2025年1月1日（周三）</strong>，共3天。</p><p>2024年12月29日（周日）正常上班。</p><p>祝大家元旦快乐，假期愉快！</p>', 4, 'M', 1, NULL, 1, 1, '2024-12-25 16:00:00', NULL, 1, '2024-12-25 16:00:00', 1, '2024-12-25 16:00:00', 0);
INSERT INTO sys_notice VALUES (5, '新产品发布会邀请', '<p>🎊 新产品发布会邀请</p><p>公司将于 <strong>2025年1月15日下午14:00</strong> 在总部会议室举办新产品发布会。</p><p>届时将展示最新研发的产品和技术成果，欢迎全体员工参加。</p><p>请各部门提前安排好工作，准时参加。</p>', 5, 'M', 1, NULL, 1, 1, '2024-12-28 11:00:00', NULL, 1, '2024-12-28 11:00:00', 1, '2024-12-28 11:00:00', 0);
INSERT INTO sys_notice VALUES (6, 'v2.16.1 版本更新', '<p>✨ 版本更新</p><p>v2.16.1 版本已发布，主要修复内容：</p><p>1. 修复 WebSocket 重复连接导致的后台线程阻塞问题</p><p>2. 优化通知公告功能，提升用户体验</p><p>3. 修复部分已知bug</p><p>建议尽快更新到最新版本。</p>', 1, 'M', 1, NULL, 1, 1, '2024-12-05 15:30:00', NULL, 1, '2024-12-05 15:30:00', 1, '2024-12-05 15:30:00', 0);
INSERT INTO sys_notice VALUES (7, '年终总结会议通知', '<p>📋 年终总结会议通知</p><p>各部门年终总结会议将于 <strong>2024年12月30日上午9:00</strong> 召开。</p><p>请各部门负责人提前准备好年度工作总结和下年度工作计划。</p><p>会议地点：总部大会议室</p>', 5, 'M', 2, '1,2', 1, 1, '2024-12-22 10:00:00', NULL, 1, '2024-12-22 10:00:00', 1, '2024-12-22 10:00:00', 0);
INSERT INTO sys_notice VALUES (8, '系统功能优化完成', '<p>✅ 系统功能优化</p><p>已完成以下功能优化：</p><p>1. 优化用户管理界面，提升操作体验</p><p>2. 增强数据导出功能，支持更多格式</p><p>3. 优化搜索功能，提升查询效率</p><p>4. 修复部分界面显示问题</p>', 1, 'L', 1, NULL, 1, 1, '2024-12-12 14:20:00', NULL, 1, '2024-12-12 14:20:00', 1, '2024-12-12 14:20:00', 0);
INSERT INTO sys_notice VALUES (9, '员工培训计划', '<p>📚 员工培训计划</p><p>为提升员工专业技能，公司将于 <strong>2025年1月8日-10日</strong> 组织技术培训。</p><p>培训内容：</p><p>1. 新技术框架应用</p><p>2. 代码规范与最佳实践</p><p>3. 系统架构设计</p><p>请各部门合理安排工作，确保培训顺利进行。</p>', 5, 'M', 1, NULL, 1, 1, '2024-12-20 09:30:00', NULL, 1, '2024-12-20 09:30:00', 1, '2024-12-20 09:30:00', 0);
INSERT INTO sys_notice VALUES (10, '数据备份提醒', '<p>💾 数据备份提醒</p><p>请各部门注意定期备份重要数据，建议每周至少备份一次。</p><p>备份方式：</p><p>1. 使用系统自带备份功能</p><p>2. 手动导出重要数据</p><p>3. 联系IT部门协助备份</p><p>数据安全，人人有责！</p>', 3, 'L', 1, NULL, 1, 1, '2024-12-08 08:00:00', NULL, 1, '2024-12-08 08:00:00', 1, '2024-12-08 08:00:00', 0);

INSERT INTO sys_role VALUES (1, '超级管理员', 'ROOT', 1, 1, 1, NULL, '2026-07-30 20:08:41.930657', NULL, '2026-07-30 20:08:41.930657', 0);
INSERT INTO sys_role VALUES (2, '系统管理员', 'ADMIN', 2, 1, 1, NULL, '2026-07-30 20:08:41.931815', NULL, NULL, 0);
INSERT INTO sys_role VALUES (3, '访问游客', 'GUEST', 3, 1, 3, NULL, '2026-07-30 20:08:41.932563', NULL, '2026-07-30 20:08:41.932563', 0);
INSERT INTO sys_role VALUES (4, '部门主管', 'DEPT_MANAGER', 4, 1, 2, NULL, '2026-07-30 20:08:41.933173', NULL, '2026-07-30 20:08:41.933173', 0);
INSERT INTO sys_role VALUES (5, '部门成员', 'DEPT_MEMBER', 5, 1, 3, NULL, '2026-07-30 20:08:41.933789', NULL, '2026-07-30 20:08:41.933789', 0);
INSERT INTO sys_role VALUES (6, '普通员工', 'EMPLOYEE', 6, 1, 4, NULL, '2026-07-30 20:08:41.934415', NULL, '2026-07-30 20:08:41.934415', 0);
INSERT INTO sys_role VALUES (7, '自定义权限用户', 'CUSTOM_USER', 7, 1, 5, NULL, '2026-07-30 20:08:41.935091', NULL, '2026-07-30 20:08:41.935091', 0);

INSERT INTO sys_role_dept VALUES (7, 1);
INSERT INTO sys_role_dept VALUES (7, 2);

INSERT INTO sys_role_menu VALUES (2, 1);
INSERT INTO sys_role_menu VALUES (2, 210);
INSERT INTO sys_role_menu VALUES (2, 2101);
INSERT INTO sys_role_menu VALUES (2, 2102);
INSERT INTO sys_role_menu VALUES (2, 2103);
INSERT INTO sys_role_menu VALUES (2, 2104);
INSERT INTO sys_role_menu VALUES (2, 2105);
INSERT INTO sys_role_menu VALUES (2, 2106);
INSERT INTO sys_role_menu VALUES (2, 2107);
INSERT INTO sys_role_menu VALUES (2, 220);
INSERT INTO sys_role_menu VALUES (2, 2201);
INSERT INTO sys_role_menu VALUES (2, 2202);
INSERT INTO sys_role_menu VALUES (2, 2203);
INSERT INTO sys_role_menu VALUES (2, 2204);
INSERT INTO sys_role_menu VALUES (2, 2205);
INSERT INTO sys_role_menu VALUES (2, 230);
INSERT INTO sys_role_menu VALUES (2, 2301);
INSERT INTO sys_role_menu VALUES (2, 2302);
INSERT INTO sys_role_menu VALUES (2, 2303);
INSERT INTO sys_role_menu VALUES (2, 2304);
INSERT INTO sys_role_menu VALUES (2, 240);
INSERT INTO sys_role_menu VALUES (2, 2401);
INSERT INTO sys_role_menu VALUES (2, 2402);
INSERT INTO sys_role_menu VALUES (2, 2403);
INSERT INTO sys_role_menu VALUES (2, 2404);
INSERT INTO sys_role_menu VALUES (2, 250);
INSERT INTO sys_role_menu VALUES (2, 2501);
INSERT INTO sys_role_menu VALUES (2, 2502);
INSERT INTO sys_role_menu VALUES (2, 2503);
INSERT INTO sys_role_menu VALUES (2, 2504);
INSERT INTO sys_role_menu VALUES (2, 251);
INSERT INTO sys_role_menu VALUES (2, 2511);
INSERT INTO sys_role_menu VALUES (2, 2512);
INSERT INTO sys_role_menu VALUES (2, 2513);
INSERT INTO sys_role_menu VALUES (2, 2514);
INSERT INTO sys_role_menu VALUES (2, 260);
INSERT INTO sys_role_menu VALUES (2, 2601);
INSERT INTO sys_role_menu VALUES (2, 270);
INSERT INTO sys_role_menu VALUES (2, 2701);
INSERT INTO sys_role_menu VALUES (2, 2702);
INSERT INTO sys_role_menu VALUES (2, 2703);
INSERT INTO sys_role_menu VALUES (2, 2704);
INSERT INTO sys_role_menu VALUES (2, 2705);
INSERT INTO sys_role_menu VALUES (2, 280);
INSERT INTO sys_role_menu VALUES (2, 2801);
INSERT INTO sys_role_menu VALUES (2, 2802);
INSERT INTO sys_role_menu VALUES (2, 2803);
INSERT INTO sys_role_menu VALUES (2, 2804);
INSERT INTO sys_role_menu VALUES (2, 2805);
INSERT INTO sys_role_menu VALUES (2, 2806);
INSERT INTO sys_role_menu VALUES (7, 1);
INSERT INTO sys_role_menu VALUES (7, 210);
INSERT INTO sys_role_menu VALUES (7, 2101);
INSERT INTO sys_role_menu VALUES (7, 2102);
INSERT INTO sys_role_menu VALUES (7, 2103);
INSERT INTO sys_role_menu VALUES (7, 2104);
INSERT INTO sys_role_menu VALUES (7, 2105);
INSERT INTO sys_role_menu VALUES (7, 2106);
INSERT INTO sys_role_menu VALUES (7, 2107);
INSERT INTO sys_role_menu VALUES (7, 220);
INSERT INTO sys_role_menu VALUES (7, 2201);
INSERT INTO sys_role_menu VALUES (7, 2202);
INSERT INTO sys_role_menu VALUES (7, 2203);
INSERT INTO sys_role_menu VALUES (7, 2204);
INSERT INTO sys_role_menu VALUES (7, 2205);
INSERT INTO sys_role_menu VALUES (2, 3000);
INSERT INTO sys_role_menu VALUES (2, 3010);
INSERT INTO sys_role_menu VALUES (2, 3011);
INSERT INTO sys_role_menu VALUES (2, 3012);
INSERT INTO sys_role_menu VALUES (2, 3013);
INSERT INTO sys_role_menu VALUES (2, 3014);
INSERT INTO sys_role_menu VALUES (2, 3015);
INSERT INTO sys_role_menu VALUES (2, 3016);
INSERT INTO sys_role_menu VALUES (2, 3017);
INSERT INTO sys_role_menu VALUES (2, 3018);
INSERT INTO sys_role_menu VALUES (2, 3019);
INSERT INTO sys_role_menu VALUES (2, 3020);
INSERT INTO sys_role_menu VALUES (2, 3021);
INSERT INTO sys_role_menu VALUES (2, 3022);
INSERT INTO sys_role_menu VALUES (2, 3023);
INSERT INTO sys_role_menu VALUES (2, 3030);
INSERT INTO sys_role_menu VALUES (2, 3031);
INSERT INTO sys_role_menu VALUES (2, 3032);
INSERT INTO sys_role_menu VALUES (2, 3033);
INSERT INTO sys_role_menu VALUES (2, 3034);
INSERT INTO sys_role_menu VALUES (2, 3040);
INSERT INTO sys_role_menu VALUES (2, 3041);
INSERT INTO sys_role_menu VALUES (2, 3042);
INSERT INTO sys_role_menu VALUES (2, 3043);
INSERT INTO sys_role_menu VALUES (2, 3044);
INSERT INTO sys_role_menu VALUES (2, 3060);
INSERT INTO sys_role_menu VALUES (2, 3070);
INSERT INTO sys_role_menu VALUES (2, 3071);
INSERT INTO sys_role_menu VALUES (2, 3072);
INSERT INTO sys_role_menu VALUES (1, 3000);
INSERT INTO sys_role_menu VALUES (1, 3010);
INSERT INTO sys_role_menu VALUES (1, 3011);
INSERT INTO sys_role_menu VALUES (1, 3012);
INSERT INTO sys_role_menu VALUES (1, 3013);
INSERT INTO sys_role_menu VALUES (1, 3014);
INSERT INTO sys_role_menu VALUES (1, 3015);
INSERT INTO sys_role_menu VALUES (1, 3016);
INSERT INTO sys_role_menu VALUES (1, 3017);
INSERT INTO sys_role_menu VALUES (1, 3018);
INSERT INTO sys_role_menu VALUES (1, 3019);
INSERT INTO sys_role_menu VALUES (1, 3020);
INSERT INTO sys_role_menu VALUES (1, 3021);
INSERT INTO sys_role_menu VALUES (1, 3022);
INSERT INTO sys_role_menu VALUES (1, 3023);
INSERT INTO sys_role_menu VALUES (1, 3030);
INSERT INTO sys_role_menu VALUES (1, 3031);
INSERT INTO sys_role_menu VALUES (1, 3032);
INSERT INTO sys_role_menu VALUES (1, 3033);
INSERT INTO sys_role_menu VALUES (1, 3034);
INSERT INTO sys_role_menu VALUES (1, 3040);
INSERT INTO sys_role_menu VALUES (1, 3041);
INSERT INTO sys_role_menu VALUES (1, 3042);
INSERT INTO sys_role_menu VALUES (1, 3043);
INSERT INTO sys_role_menu VALUES (1, 3044);
INSERT INTO sys_role_menu VALUES (1, 3060);
INSERT INTO sys_role_menu VALUES (1, 3070);
INSERT INTO sys_role_menu VALUES (1, 3071);
INSERT INTO sys_role_menu VALUES (1, 3072);
INSERT INTO sys_role_menu VALUES (1, 3080);
INSERT INTO sys_role_menu VALUES (2, 3080);
INSERT INTO sys_role_menu VALUES (1, 3081);
INSERT INTO sys_role_menu VALUES (2, 3081);
INSERT INTO sys_role_menu VALUES (1, 3082);
INSERT INTO sys_role_menu VALUES (2, 3082);
INSERT INTO sys_role_menu VALUES (1, 3083);
INSERT INTO sys_role_menu VALUES (2, 3083);
INSERT INTO sys_role_menu VALUES (1, 3084);
INSERT INTO sys_role_menu VALUES (2, 3084);
INSERT INTO sys_role_menu VALUES (1, 3024);
INSERT INTO sys_role_menu VALUES (2, 3024);
INSERT INTO sys_role_menu VALUES (1, 3025);
INSERT INTO sys_role_menu VALUES (2, 3025);
INSERT INTO sys_role_menu VALUES (6, 3000);
INSERT INTO sys_role_menu VALUES (6, 3010);
INSERT INTO sys_role_menu VALUES (6, 3011);
INSERT INTO sys_role_menu VALUES (6, 3012);
INSERT INTO sys_role_menu VALUES (6, 3013);
INSERT INTO sys_role_menu VALUES (6, 3014);
INSERT INTO sys_role_menu VALUES (6, 3015);
INSERT INTO sys_role_menu VALUES (6, 3016);
INSERT INTO sys_role_menu VALUES (6, 3017);
INSERT INTO sys_role_menu VALUES (6, 3018);
INSERT INTO sys_role_menu VALUES (6, 3019);
INSERT INTO sys_role_menu VALUES (6, 3024);
INSERT INTO sys_role_menu VALUES (6, 3020);
INSERT INTO sys_role_menu VALUES (6, 3021);
INSERT INTO sys_role_menu VALUES (6, 3022);
INSERT INTO sys_role_menu VALUES (6, 3023);
INSERT INTO sys_role_menu VALUES (6, 3025);
INSERT INTO sys_role_menu VALUES (6, 3040);
INSERT INTO sys_role_menu VALUES (6, 3041);
INSERT INTO sys_role_menu VALUES (6, 3042);
INSERT INTO sys_role_menu VALUES (6, 3043);
INSERT INTO sys_role_menu VALUES (6, 3044);
INSERT INTO sys_role_menu VALUES (6, 3060);
INSERT INTO sys_role_menu VALUES (6, 3070);
INSERT INTO sys_role_menu VALUES (6, 3071);
INSERT INTO sys_role_menu VALUES (6, 3072);
INSERT INTO sys_role_menu VALUES (6, 3080);
INSERT INTO sys_role_menu VALUES (6, 3081);
INSERT INTO sys_role_menu VALUES (6, 3082);
INSERT INTO sys_role_menu VALUES (6, 3083);
INSERT INTO sys_role_menu VALUES (6, 3084);
INSERT INTO sys_role_menu VALUES (6, 1);
INSERT INTO sys_role_menu VALUES (6, 210);
INSERT INTO sys_role_menu VALUES (6, 2101);
INSERT INTO sys_role_menu VALUES (6, 2102);
INSERT INTO sys_role_menu VALUES (6, 2103);
INSERT INTO sys_role_menu VALUES (6, 2104);
INSERT INTO sys_role_menu VALUES (6, 2105);
INSERT INTO sys_role_menu VALUES (6, 2106);
INSERT INTO sys_role_menu VALUES (6, 2107);
INSERT INTO sys_role_menu VALUES (6, 220);
INSERT INTO sys_role_menu VALUES (6, 2201);
INSERT INTO sys_role_menu VALUES (6, 2202);
INSERT INTO sys_role_menu VALUES (6, 2203);
INSERT INTO sys_role_menu VALUES (6, 2204);
INSERT INTO sys_role_menu VALUES (6, 2205);
INSERT INTO sys_role_menu VALUES (4, 3000);
INSERT INTO sys_role_menu VALUES (4, 3010);
INSERT INTO sys_role_menu VALUES (4, 3011);
INSERT INTO sys_role_menu VALUES (4, 3012);
INSERT INTO sys_role_menu VALUES (4, 3013);
INSERT INTO sys_role_menu VALUES (4, 3014);
INSERT INTO sys_role_menu VALUES (4, 3015);
INSERT INTO sys_role_menu VALUES (4, 3016);
INSERT INTO sys_role_menu VALUES (4, 3017);
INSERT INTO sys_role_menu VALUES (4, 3018);
INSERT INTO sys_role_menu VALUES (4, 3019);
INSERT INTO sys_role_menu VALUES (4, 3024);
INSERT INTO sys_role_menu VALUES (4, 3020);
INSERT INTO sys_role_menu VALUES (4, 3021);
INSERT INTO sys_role_menu VALUES (4, 3022);
INSERT INTO sys_role_menu VALUES (4, 3023);
INSERT INTO sys_role_menu VALUES (4, 3025);
INSERT INTO sys_role_menu VALUES (4, 3040);
INSERT INTO sys_role_menu VALUES (4, 3041);
INSERT INTO sys_role_menu VALUES (4, 3042);
INSERT INTO sys_role_menu VALUES (4, 3043);
INSERT INTO sys_role_menu VALUES (4, 3044);
INSERT INTO sys_role_menu VALUES (4, 3060);
INSERT INTO sys_role_menu VALUES (4, 3070);
INSERT INTO sys_role_menu VALUES (4, 3071);
INSERT INTO sys_role_menu VALUES (4, 3072);
INSERT INTO sys_role_menu VALUES (4, 3080);
INSERT INTO sys_role_menu VALUES (4, 3081);
INSERT INTO sys_role_menu VALUES (4, 3082);
INSERT INTO sys_role_menu VALUES (4, 3083);
INSERT INTO sys_role_menu VALUES (4, 3084);
INSERT INTO sys_role_menu VALUES (4, 1);
INSERT INTO sys_role_menu VALUES (4, 210);
INSERT INTO sys_role_menu VALUES (4, 2101);
INSERT INTO sys_role_menu VALUES (4, 2102);
INSERT INTO sys_role_menu VALUES (4, 2103);
INSERT INTO sys_role_menu VALUES (4, 2104);
INSERT INTO sys_role_menu VALUES (4, 2105);
INSERT INTO sys_role_menu VALUES (4, 2106);
INSERT INTO sys_role_menu VALUES (4, 2107);
INSERT INTO sys_role_menu VALUES (4, 220);
INSERT INTO sys_role_menu VALUES (4, 2201);
INSERT INTO sys_role_menu VALUES (4, 2202);
INSERT INTO sys_role_menu VALUES (4, 2203);
INSERT INTO sys_role_menu VALUES (4, 2204);
INSERT INTO sys_role_menu VALUES (4, 2205);
INSERT INTO sys_role_menu VALUES (5, 3000);
INSERT INTO sys_role_menu VALUES (5, 3010);
INSERT INTO sys_role_menu VALUES (5, 3011);
INSERT INTO sys_role_menu VALUES (5, 3012);
INSERT INTO sys_role_menu VALUES (5, 3013);
INSERT INTO sys_role_menu VALUES (5, 3014);
INSERT INTO sys_role_menu VALUES (5, 3015);
INSERT INTO sys_role_menu VALUES (5, 3016);
INSERT INTO sys_role_menu VALUES (5, 3017);
INSERT INTO sys_role_menu VALUES (5, 3018);
INSERT INTO sys_role_menu VALUES (5, 3019);
INSERT INTO sys_role_menu VALUES (5, 3024);
INSERT INTO sys_role_menu VALUES (5, 3020);
INSERT INTO sys_role_menu VALUES (5, 3021);
INSERT INTO sys_role_menu VALUES (5, 3022);
INSERT INTO sys_role_menu VALUES (5, 3023);
INSERT INTO sys_role_menu VALUES (5, 3025);
INSERT INTO sys_role_menu VALUES (5, 3040);
INSERT INTO sys_role_menu VALUES (5, 3041);
INSERT INTO sys_role_menu VALUES (5, 3042);
INSERT INTO sys_role_menu VALUES (5, 3043);
INSERT INTO sys_role_menu VALUES (5, 3044);
INSERT INTO sys_role_menu VALUES (5, 3060);
INSERT INTO sys_role_menu VALUES (5, 3070);
INSERT INTO sys_role_menu VALUES (5, 3071);
INSERT INTO sys_role_menu VALUES (5, 3072);
INSERT INTO sys_role_menu VALUES (5, 3080);
INSERT INTO sys_role_menu VALUES (5, 3081);
INSERT INTO sys_role_menu VALUES (5, 3082);
INSERT INTO sys_role_menu VALUES (5, 3083);
INSERT INTO sys_role_menu VALUES (5, 3084);
INSERT INTO sys_role_menu VALUES (5, 1);
INSERT INTO sys_role_menu VALUES (5, 210);
INSERT INTO sys_role_menu VALUES (5, 2101);
INSERT INTO sys_role_menu VALUES (5, 2102);
INSERT INTO sys_role_menu VALUES (5, 2103);
INSERT INTO sys_role_menu VALUES (5, 2104);
INSERT INTO sys_role_menu VALUES (5, 2105);
INSERT INTO sys_role_menu VALUES (5, 2106);
INSERT INTO sys_role_menu VALUES (5, 2107);
INSERT INTO sys_role_menu VALUES (5, 220);
INSERT INTO sys_role_menu VALUES (5, 2201);
INSERT INTO sys_role_menu VALUES (5, 2202);
INSERT INTO sys_role_menu VALUES (5, 2203);
INSERT INTO sys_role_menu VALUES (5, 2204);
INSERT INTO sys_role_menu VALUES (5, 2205);

INSERT INTO sys_user VALUES (1, 'root', '有来技术', 0, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', NULL, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345677', 1, 'youlaitech@163.com', '2026-07-30 20:08:41.984546', NULL, '2026-07-30 20:08:41.984546', NULL, 0);
INSERT INTO sys_user VALUES (2, 'admin', '系统管理员', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18888888888', 1, 'youlaitech@163.com', '2026-07-30 20:08:41.985544', NULL, '2026-07-30 20:08:41.985544', NULL, 0);
INSERT INTO sys_user VALUES (3, 'test', '测试小用户', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 3, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345679', 1, 'youlaitech@163.com', '2026-07-30 20:08:41.986213', NULL, '2026-07-30 20:08:41.986213', NULL, 0);
INSERT INTO sys_user VALUES (4, 'dept_manager', '部门主管', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345680', 1, 'manager@youlaitech.com', '2026-07-30 20:08:41.986857', NULL, '2026-07-30 20:08:41.986857', NULL, 0);
INSERT INTO sys_user VALUES (5, 'dept_member', '部门成员', 1, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 1, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345681', 1, 'member@youlaitech.com', '2026-07-30 20:08:41.987548', NULL, '2026-07-30 20:08:41.987548', NULL, 0);
INSERT INTO sys_user VALUES (7, 'custom_user', '自定义权限用户', 2, '$2a$10$xVWsNOhHrCxh5UbpCE7/HuJ.PAOKcYAqRxD2CO2nVnJS.IAXkr5aq', 3, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345683', 1, 'custom@youlaitech.com', '2026-07-30 20:08:41.9889', NULL, '2026-07-30 21:43:38.223241', 2, 0);
INSERT INTO sys_user VALUES (6, 'employee', '普通员工', 1, '$2b$12$skFqm9l6IZA4cUQ7/K/YueeCckufs1b4nWd7H4ZcgKh9cmn/Mhi4O', 2, 'https://foruda.gitee.com/images/1723603502796844527/03cdca2a_716974.gif', '18812345682', 1, 'employee@youlaitech.com', '2026-07-30 20:08:41.988193', NULL, '2026-08-08 23:42:54.967576', NULL, 0);

INSERT INTO sys_user_notice VALUES (1, 1, 2, 1, NULL, '2026-07-30 20:08:42.110029', '2026-07-30 20:08:42.110029', 0);
INSERT INTO sys_user_notice VALUES (2, 2, 2, 1, NULL, '2026-07-30 20:08:42.110993', '2026-07-30 20:08:42.110993', 0);
INSERT INTO sys_user_notice VALUES (3, 3, 2, 1, NULL, '2026-07-30 20:08:42.111661', '2026-07-30 20:08:42.111661', 0);
INSERT INTO sys_user_notice VALUES (4, 4, 2, 1, NULL, '2026-07-30 20:08:42.112291', '2026-07-30 20:08:42.112291', 0);
INSERT INTO sys_user_notice VALUES (5, 5, 2, 1, NULL, '2026-07-30 20:08:42.112928', '2026-07-30 20:08:42.112928', 0);
INSERT INTO sys_user_notice VALUES (6, 6, 2, 1, NULL, '2026-07-30 20:08:42.113547', '2026-07-30 20:08:42.113547', 0);
INSERT INTO sys_user_notice VALUES (7, 7, 2, 1, NULL, '2026-07-30 20:08:42.11425', '2026-07-30 20:08:42.11425', 0);
INSERT INTO sys_user_notice VALUES (8, 8, 2, 1, NULL, '2026-07-30 20:08:42.115053', '2026-07-30 20:08:42.115053', 0);
INSERT INTO sys_user_notice VALUES (9, 9, 2, 1, NULL, '2026-07-30 20:08:42.115867', '2026-07-30 20:08:42.115867', 0);
INSERT INTO sys_user_notice VALUES (10, 10, 2, 1, NULL, '2026-07-30 20:08:42.116589', '2026-07-30 20:08:42.116589', 0);

INSERT INTO sys_user_role VALUES (1, 1);
INSERT INTO sys_user_role VALUES (2, 2);
INSERT INTO sys_user_role VALUES (3, 3);
INSERT INTO sys_user_role VALUES (4, 4);
INSERT INTO sys_user_role VALUES (5, 5);
INSERT INTO sys_user_role VALUES (6, 6);
INSERT INTO sys_user_role VALUES (7, 7);

-- Name: sys_config_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_dept_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_dict_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_dict_item_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_menu_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_notice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_user_notice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
-- Name: sys_user_social_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
