SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_table_access_method = heap;

-- Name: sys_config; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_config (
    id bigint NOT NULL,
    config_name character varying(50) NOT NULL,
    config_key character varying(50) NOT NULL,
    config_value character varying(100) NOT NULL,
    remark character varying(255),
    create_time timestamp without time zone,
    create_by bigint,
    update_time timestamp without time zone,
    update_by bigint,
    is_deleted smallint DEFAULT 0 NOT NULL
);

-- Name: TABLE sys_config; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_config IS '系统配置表';

-- Name: COLUMN sys_config.config_name; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.config_name IS '配置名称';

-- Name: COLUMN sys_config.config_key; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.config_key IS '配置key';

-- Name: COLUMN sys_config.config_value; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.config_value IS '配置值';

-- Name: COLUMN sys_config.remark; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.remark IS '备注';

-- Name: COLUMN sys_config.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.create_time IS '创建时间';

-- Name: COLUMN sys_config.create_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.create_by IS '创建人ID';

-- Name: COLUMN sys_config.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.update_time IS '更新时间';

-- Name: COLUMN sys_config.update_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.update_by IS '更新人ID';

-- Name: COLUMN sys_config.is_deleted; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_config.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';

-- Name: sys_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_dept; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_dept (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(100) NOT NULL,
    parent_id bigint DEFAULT 0,
    tree_path character varying(255) NOT NULL,
    sort smallint DEFAULT 0,
    status smallint DEFAULT 1,
    create_by bigint,
    create_time timestamp without time zone,
    update_by bigint,
    update_time timestamp without time zone,
    is_deleted smallint DEFAULT 0
);

-- Name: TABLE sys_dept; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_dept IS '部门管理表';

-- Name: COLUMN sys_dept.id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.id IS '主键';

-- Name: COLUMN sys_dept.name; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.name IS '部门名称';

-- Name: COLUMN sys_dept.code; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.code IS '部门编号';

-- Name: COLUMN sys_dept.parent_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.parent_id IS '父节点id';

-- Name: COLUMN sys_dept.tree_path; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.tree_path IS '父节点id路径';

-- Name: COLUMN sys_dept.sort; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.sort IS '显示顺序';

-- Name: COLUMN sys_dept.status; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.status IS '状态(1-正常 0-禁用)';

-- Name: COLUMN sys_dept.create_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.create_by IS '创建人ID';

-- Name: COLUMN sys_dept.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.create_time IS '创建时间';

-- Name: COLUMN sys_dept.update_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.update_by IS '修改人ID';

-- Name: COLUMN sys_dept.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.update_time IS '更新时间';

-- Name: COLUMN sys_dept.is_deleted; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dept.is_deleted IS '逻辑删除标识(1-已删除 0-未删除)';

-- Name: sys_dept_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_dept ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_dept_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_dict; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_dict (
    id bigint NOT NULL,
    dict_code character varying(50),
    name character varying(50),
    status smallint DEFAULT 0,
    remark character varying(255),
    create_time timestamp without time zone,
    create_by bigint,
    update_time timestamp without time zone,
    update_by bigint,
    is_deleted smallint DEFAULT 0
);

-- Name: TABLE sys_dict; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_dict IS '数据字典类型表';

-- Name: COLUMN sys_dict.id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.id IS '主键 ';

-- Name: COLUMN sys_dict.dict_code; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.dict_code IS '类型编码';

-- Name: COLUMN sys_dict.name; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.name IS '类型名称';

-- Name: COLUMN sys_dict.status; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.status IS '状态(0:正常;1:禁用)';

-- Name: COLUMN sys_dict.remark; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.remark IS '备注';

-- Name: COLUMN sys_dict.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.create_time IS '创建时间';

-- Name: COLUMN sys_dict.create_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.create_by IS '创建人ID';

-- Name: COLUMN sys_dict.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.update_time IS '更新时间';

-- Name: COLUMN sys_dict.update_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.update_by IS '修改人ID';

-- Name: COLUMN sys_dict.is_deleted; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict.is_deleted IS '是否删除(1-删除，0-未删除)';

-- Name: sys_dict_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_dict ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_dict_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_dict_item; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_dict_item (
    id bigint NOT NULL,
    dict_code character varying(50),
    value character varying(50),
    label character varying(100),
    tag_type character varying(50),
    status smallint DEFAULT 0,
    sort integer DEFAULT 0,
    remark character varying(255),
    create_time timestamp without time zone,
    create_by bigint,
    update_time timestamp without time zone,
    update_by bigint
);

-- Name: TABLE sys_dict_item; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_dict_item IS '数据字典项表';

-- Name: COLUMN sys_dict_item.id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.id IS '主键';

-- Name: COLUMN sys_dict_item.dict_code; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.dict_code IS '关联字典编码，与sys_dict表中的dict_code对应';

-- Name: COLUMN sys_dict_item.value; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.value IS '字典项值';

-- Name: COLUMN sys_dict_item.label; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.label IS '字典项标签';

-- Name: COLUMN sys_dict_item.tag_type; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.tag_type IS '标签类型，用于前端样式展示（如success、warning等）';

-- Name: COLUMN sys_dict_item.status; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.status IS '状态（1-正常，0-禁用）';

-- Name: COLUMN sys_dict_item.sort; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.sort IS '排序';

-- Name: COLUMN sys_dict_item.remark; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.remark IS '备注';

-- Name: COLUMN sys_dict_item.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.create_time IS '创建时间';

-- Name: COLUMN sys_dict_item.create_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.create_by IS '创建人ID';

-- Name: COLUMN sys_dict_item.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.update_time IS '更新时间';

-- Name: COLUMN sys_dict_item.update_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_dict_item.update_by IS '修改人ID';

-- Name: sys_dict_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_dict_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_dict_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_log; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_log (
    id bigint NOT NULL,
    module smallint NOT NULL,
    action_type smallint NOT NULL,
    title character varying(100) NOT NULL,
    content text,
    operator_id bigint,
    operator_name character varying(50),
    request_uri character varying(255),
    request_method character varying(10),
    ip character varying(45),
    province character varying(100),
    city character varying(100),
    device character varying(100),
    os character varying(100),
    browser character varying(100),
    status smallint DEFAULT 1,
    error_msg character varying(255),
    execution_time integer,
    create_time timestamp without time zone
);

-- Name: TABLE sys_log; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_log IS '系统操作日志表';

-- Name: COLUMN sys_log.id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.id IS '主键';

-- Name: COLUMN sys_log.module; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.module IS '模块，数字枚举，参考 LogModule 枚举';

-- Name: COLUMN sys_log.action_type; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.action_type IS '操作类型，数字枚举，参考 ActionType 枚举';

-- Name: COLUMN sys_log.title; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.title IS '前端显示标题';

-- Name: COLUMN sys_log.content; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.content IS '自定义日志内容';

-- Name: COLUMN sys_log.operator_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.operator_id IS '操作人ID';

-- Name: COLUMN sys_log.operator_name; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.operator_name IS '操作人名称';

-- Name: COLUMN sys_log.request_uri; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.request_uri IS '请求路径';

-- Name: COLUMN sys_log.request_method; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.request_method IS '请求方法';

-- Name: COLUMN sys_log.ip; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.ip IS 'IP地址';

-- Name: COLUMN sys_log.province; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.province IS '省份';

-- Name: COLUMN sys_log.city; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.city IS '城市';

-- Name: COLUMN sys_log.device; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.device IS '设备';

-- Name: COLUMN sys_log.os; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.os IS '操作系统';

-- Name: COLUMN sys_log.browser; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.browser IS '浏览器';

-- Name: COLUMN sys_log.status; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.status IS '0失败 1成功';

-- Name: COLUMN sys_log.error_msg; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.error_msg IS '错误信息';

-- Name: COLUMN sys_log.execution_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.execution_time IS '执行时间(ms)';

-- Name: COLUMN sys_log.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_log.create_time IS '操作时间';

-- Name: sys_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_menu; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_menu (
    id bigint NOT NULL,
    parent_id bigint NOT NULL,
    tree_path character varying(255),
    name character varying(64) NOT NULL,
    type character(1) NOT NULL,
    route_name character varying(255),
    route_path character varying(128),
    component character varying(128),
    perm character varying(128),
    external_url character varying(512),
    always_show smallint DEFAULT 0,
    keep_alive smallint DEFAULT 0,
    visible smallint DEFAULT 1,
    sort integer DEFAULT 0,
    icon character varying(64),
    redirect character varying(128),
    create_time timestamp without time zone,
    update_time timestamp without time zone,
    params jsonb
);

-- Name: TABLE sys_menu; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_menu IS '系统菜单表';

-- Name: COLUMN sys_menu.id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.id IS 'ID';

-- Name: COLUMN sys_menu.parent_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.parent_id IS '父菜单ID';

-- Name: COLUMN sys_menu.tree_path; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.tree_path IS '父节点ID路径';

-- Name: COLUMN sys_menu.name; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.name IS '菜单名称';

-- Name: COLUMN sys_menu.type; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.type IS '菜单类型（C-目录 M-菜单 E-外链 B-按钮）';

-- Name: COLUMN sys_menu.route_name; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.route_name IS '路由名称（Vue Router 中用于命名路由）';

-- Name: COLUMN sys_menu.route_path; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.route_path IS '路由路径（Vue Router 中定义的 URL 路径）';

-- Name: COLUMN sys_menu.component; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.component IS '组件路径（组件页面完整路径，相对于 src/views/，缺省后缀 .vue）';

-- Name: COLUMN sys_menu.perm; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.perm IS '【按钮】权限标识';

-- Name: COLUMN sys_menu.external_url; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.external_url IS '外链地址';

-- Name: COLUMN sys_menu.always_show; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.always_show IS '【目录】只有一个子路由是否始终显示（1-是 0-否）';

-- Name: COLUMN sys_menu.keep_alive; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.keep_alive IS '【菜单】是否开启页面缓存（1-是 0-否）';

-- Name: COLUMN sys_menu.visible; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.visible IS '显示状态（1-显示 0-隐藏）';

-- Name: COLUMN sys_menu.sort; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.sort IS '排序';

-- Name: COLUMN sys_menu.icon; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.icon IS '菜单图标';

-- Name: COLUMN sys_menu.redirect; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.redirect IS '跳转路径';

-- Name: COLUMN sys_menu.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.create_time IS '创建时间';

-- Name: COLUMN sys_menu.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.update_time IS '更新时间';

-- Name: COLUMN sys_menu.params; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_menu.params IS '路由参数';

-- Name: sys_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_menu ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_notice; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_notice (
    id bigint NOT NULL,
    title character varying(50),
    content text,
    type smallint NOT NULL,
    level character varying(5) NOT NULL,
    target_type smallint NOT NULL,
    target_user_ids character varying(255),
    publisher_id bigint,
    publish_status smallint DEFAULT 0,
    publish_time timestamp without time zone,
    revoke_time timestamp without time zone,
    create_by bigint NOT NULL,
    create_time timestamp without time zone NOT NULL,
    update_by bigint,
    update_time timestamp without time zone,
    is_deleted smallint DEFAULT 0
);

-- Name: TABLE sys_notice; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_notice IS '系统通知公告表';

-- Name: COLUMN sys_notice.title; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.title IS '通知标题';

-- Name: COLUMN sys_notice.content; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.content IS '通知内容';

-- Name: COLUMN sys_notice.type; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.type IS '通知类型（关联字典编码：notice_type）';

-- Name: COLUMN sys_notice.level; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.level IS '通知等级（字典code：notice_level）';

-- Name: COLUMN sys_notice.target_type; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.target_type IS '目标类型（1: 全体, 2: 指定）';

-- Name: COLUMN sys_notice.target_user_ids; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.target_user_ids IS '目标人ID集合（多个使用英文逗号,分割）';

-- Name: COLUMN sys_notice.publisher_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.publisher_id IS '发布人ID';

-- Name: COLUMN sys_notice.publish_status; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.publish_status IS '发布状态（0: 未发布, 1: 已发布, -1: 已撤回）';

-- Name: COLUMN sys_notice.publish_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.publish_time IS '发布时间';

-- Name: COLUMN sys_notice.revoke_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.revoke_time IS '撤回时间';

-- Name: COLUMN sys_notice.create_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.create_by IS '创建人ID';

-- Name: COLUMN sys_notice.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.create_time IS '创建时间';

-- Name: COLUMN sys_notice.update_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.update_by IS '更新人ID';

-- Name: COLUMN sys_notice.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.update_time IS '更新时间';

-- Name: COLUMN sys_notice.is_deleted; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_notice.is_deleted IS '是否删除（0: 未删除, 1: 已删除）';

-- Name: sys_notice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_notice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_role; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_role (
    id bigint NOT NULL,
    name character varying(64) NOT NULL,
    code character varying(32) NOT NULL,
    sort integer,
    status smallint DEFAULT 1,
    data_scope smallint,
    create_by bigint,
    create_time timestamp without time zone,
    update_by bigint,
    update_time timestamp without time zone,
    is_deleted smallint DEFAULT 0
);

-- Name: TABLE sys_role; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_role IS '系统角色表';

-- Name: COLUMN sys_role.name; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.name IS '角色名称';

-- Name: COLUMN sys_role.code; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.code IS '角色编码';

-- Name: COLUMN sys_role.sort; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.sort IS '显示顺序';

-- Name: COLUMN sys_role.status; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.status IS '角色状态(1-正常 0-停用)';

-- Name: COLUMN sys_role.data_scope; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.data_scope IS '数据权限(1-所有数据 2-部门及子部门数据 3-本部门数据 4-本人数据 5-自定义部门数据)';

-- Name: COLUMN sys_role.create_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.create_by IS '创建人 ID';

-- Name: COLUMN sys_role.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.create_time IS '创建时间';

-- Name: COLUMN sys_role.update_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.update_by IS '更新人ID';

-- Name: COLUMN sys_role.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.update_time IS '更新时间';

-- Name: COLUMN sys_role.is_deleted; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';

-- Name: sys_role_dept; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_role_dept (
    role_id bigint NOT NULL,
    dept_id bigint NOT NULL
);

-- Name: TABLE sys_role_dept; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_role_dept IS '角色部门关联表';

-- Name: COLUMN sys_role_dept.role_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role_dept.role_id IS '角色ID';

-- Name: COLUMN sys_role_dept.dept_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role_dept.dept_id IS '部门ID';

-- Name: sys_role_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_role_menu; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_role_menu (
    role_id bigint NOT NULL,
    menu_id bigint NOT NULL
);

-- Name: TABLE sys_role_menu; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_role_menu IS '角色菜单关联表';

-- Name: COLUMN sys_role_menu.role_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role_menu.role_id IS '角色ID';

-- Name: COLUMN sys_role_menu.menu_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_role_menu.menu_id IS '菜单ID';

-- Name: sys_user; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_user (
    id bigint NOT NULL,
    username character varying(64),
    nickname character varying(64),
    gender smallint DEFAULT 1,
    password character varying(100),
    dept_id bigint,
    avatar character varying(255),
    mobile character varying(20),
    status smallint DEFAULT 1,
    email character varying(128),
    create_time timestamp without time zone,
    create_by bigint,
    update_time timestamp without time zone,
    update_by bigint,
    is_deleted smallint DEFAULT 0
);

-- Name: TABLE sys_user; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_user IS '系统用户表';

-- Name: COLUMN sys_user.username; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.username IS '用户名';

-- Name: COLUMN sys_user.nickname; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.nickname IS '昵称';

-- Name: COLUMN sys_user.gender; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.gender IS '性别((1-男 2-女 0-保密)';

-- Name: COLUMN sys_user.password; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.password IS '密码';

-- Name: COLUMN sys_user.dept_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.dept_id IS '部门ID';

-- Name: COLUMN sys_user.avatar; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.avatar IS '用户头像';

-- Name: COLUMN sys_user.mobile; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.mobile IS '联系方式';

-- Name: COLUMN sys_user.status; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.status IS '状态(1-正常 0-禁用)';

-- Name: COLUMN sys_user.email; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.email IS '用户邮箱';

-- Name: COLUMN sys_user.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.create_time IS '创建时间';

-- Name: COLUMN sys_user.create_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.create_by IS '创建人ID';

-- Name: COLUMN sys_user.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.update_time IS '更新时间';

-- Name: COLUMN sys_user.update_by; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.update_by IS '修改人ID';

-- Name: COLUMN sys_user.is_deleted; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user.is_deleted IS '逻辑删除标识(0-未删除 1-已删除)';

-- Name: sys_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_user_notice; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_user_notice (
    id bigint NOT NULL,
    notice_id bigint NOT NULL,
    user_id bigint NOT NULL,
    is_read smallint DEFAULT 0,
    read_time timestamp without time zone,
    create_time timestamp without time zone NOT NULL,
    update_time timestamp without time zone,
    is_deleted smallint DEFAULT 0
);

-- Name: TABLE sys_user_notice; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_user_notice IS '用户通知公告关联表';

-- Name: COLUMN sys_user_notice.id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_notice.id IS 'id';

-- Name: COLUMN sys_user_notice.notice_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_notice.notice_id IS '公共通知id';

-- Name: COLUMN sys_user_notice.user_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_notice.user_id IS '用户id';

-- Name: COLUMN sys_user_notice.is_read; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_notice.is_read IS '读取状态（0: 未读, 1: 已读）';

-- Name: COLUMN sys_user_notice.read_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_notice.read_time IS '阅读时间';

-- Name: COLUMN sys_user_notice.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_notice.create_time IS '创建时间';

-- Name: COLUMN sys_user_notice.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_notice.update_time IS '更新时间';

-- Name: COLUMN sys_user_notice.is_deleted; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_notice.is_deleted IS '逻辑删除(0: 未删除, 1: 已删除)';

-- Name: sys_user_notice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_user_notice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_user_notice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_user_role; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_user_role (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);

-- Name: TABLE sys_user_role; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_user_role IS '用户角色关联表';

-- Name: COLUMN sys_user_role.user_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_role.user_id IS '用户ID';

-- Name: COLUMN sys_user_role.role_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_role.role_id IS '角色ID';

-- Name: sys_user_social; Type: TABLE; Schema: public; Owner: -
CREATE TABLE public.sys_user_social (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    platform character varying(20) NOT NULL,
    openid character varying(64) NOT NULL,
    unionid character varying(64) DEFAULT NULL::character varying,
    nickname character varying(64) DEFAULT NULL::character varying,
    avatar character varying(255) DEFAULT NULL::character varying,
    session_key character varying(128) DEFAULT NULL::character varying,
    verified smallint DEFAULT 1,
    create_time timestamp without time zone,
    update_time timestamp without time zone
);

-- Name: TABLE sys_user_social; Type: COMMENT; Schema: public; Owner: -
COMMENT ON TABLE public.sys_user_social IS '用户第三方账号绑定表';

-- Name: COLUMN sys_user_social.id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.id IS '主键ID';

-- Name: COLUMN sys_user_social.user_id; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.user_id IS '用户ID';

-- Name: COLUMN sys_user_social.platform; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.platform IS '平台类型(WECHAT_MINI/WECHAT_MP/ALIPAY/QQ/APPLE)';

-- Name: COLUMN sys_user_social.openid; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.openid IS '平台openid';

-- Name: COLUMN sys_user_social.unionid; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.unionid IS '微信unionid';

-- Name: COLUMN sys_user_social.nickname; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.nickname IS '第三方昵称';

-- Name: COLUMN sys_user_social.avatar; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.avatar IS '第三方头像URL';

-- Name: COLUMN sys_user_social.session_key; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.session_key IS '微信session_key';

-- Name: COLUMN sys_user_social.verified; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.verified IS '是否已验证(1-已验证 0-未验证)';

-- Name: COLUMN sys_user_social.create_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.create_time IS '绑定时间';

-- Name: COLUMN sys_user_social.update_time; Type: COMMENT; Schema: public; Owner: -
COMMENT ON COLUMN public.sys_user_social.update_time IS '更新时间';

-- Name: sys_user_social_id_seq; Type: SEQUENCE; Schema: public; Owner: -
ALTER TABLE public.sys_user_social ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sys_user_social_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Name: sys_config sys_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_config
    ADD CONSTRAINT sys_config_pkey PRIMARY KEY (id);

-- Name: sys_dept sys_dept_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_dept
    ADD CONSTRAINT sys_dept_pkey PRIMARY KEY (id);

-- Name: sys_dict_item sys_dict_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_dict_item
    ADD CONSTRAINT sys_dict_item_pkey PRIMARY KEY (id);

-- Name: sys_dict sys_dict_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_dict
    ADD CONSTRAINT sys_dict_pkey PRIMARY KEY (id);

-- Name: sys_log sys_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_log
    ADD CONSTRAINT sys_log_pkey PRIMARY KEY (id);

-- Name: sys_menu sys_menu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_menu
    ADD CONSTRAINT sys_menu_pkey PRIMARY KEY (id);

-- Name: sys_notice sys_notice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_notice
    ADD CONSTRAINT sys_notice_pkey PRIMARY KEY (id);

-- Name: sys_role sys_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_role
    ADD CONSTRAINT sys_role_pkey PRIMARY KEY (id);

-- Name: sys_user_notice sys_user_notice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_user_notice
    ADD CONSTRAINT sys_user_notice_pkey PRIMARY KEY (id);

-- Name: sys_user sys_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_user
    ADD CONSTRAINT sys_user_pkey PRIMARY KEY (id);

-- Name: sys_user_role sys_user_role_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_user_role
    ADD CONSTRAINT sys_user_role_pkey PRIMARY KEY (user_id, role_id);

-- Name: sys_user_social sys_user_social_pkey; Type: CONSTRAINT; Schema: public; Owner: -
ALTER TABLE ONLY public.sys_user_social
    ADD CONSTRAINT sys_user_social_pkey PRIMARY KEY (id);

-- Name: idx_dict_code; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_dict_code ON public.sys_dict USING btree (dict_code);

-- Name: idx_module_action_time; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_module_action_time ON public.sys_log USING btree (module, action_type, create_time);

-- Name: idx_operator_time; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_operator_time ON public.sys_log USING btree (operator_id, create_time);

-- Name: idx_time; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_time ON public.sys_log USING btree (create_time);

-- Name: idx_unionid; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_unionid ON public.sys_user_social USING btree (unionid);

-- Name: idx_user_id; Type: INDEX; Schema: public; Owner: -
CREATE INDEX idx_user_id ON public.sys_user_social USING btree (user_id);

-- Name: uk_code; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX uk_code ON public.sys_dept USING btree (code);

-- Name: uk_name; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX uk_name ON public.sys_role USING btree (name);

-- Name: uk_platform_openid; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX uk_platform_openid ON public.sys_user_social USING btree (platform, openid);

-- Name: uk_role_code; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX uk_role_code ON public.sys_role USING btree (code);

-- Name: uk_roleid_deptid; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX uk_roleid_deptid ON public.sys_role_dept USING btree (role_id, dept_id);

-- Name: uk_roleid_menuid; Type: INDEX; Schema: public; Owner: -
CREATE UNIQUE INDEX uk_roleid_menuid ON public.sys_role_menu USING btree (role_id, menu_id);
